declare namespace cubee {
    interface IRunnable {
        (): void;
    }
    class Point2D {
        private _x;
        private _y;
        constructor(_x: number, _y: number);
        readonly x: number;
        readonly y: number;
    }
}
declare namespace cubee {
    class EventArgs {
        sender: Object;
        constructor(sender: Object);
    }
    interface IListenerCallback<T> {
        onAdded(listener: IEventListener<T>): void;
        onRemoved(listener: IEventListener<T>): void;
    }
    class HtmlEventListenerCallback<T> implements IListenerCallback<T> {
        private _element;
        private _eventType;
        constructor(_element: HTMLElement, _eventType: string);
        onAdded(listener: IEventListener<T>): void;
        onRemoved(listener: IEventListener<T>): void;
    }
    class Event<T> {
        private _listenerCallback;
        private _listeners;
        constructor(_listenerCallback?: IListenerCallback<T>);
        addListener(listener: IEventListener<T>): void;
        removeListener(listener: IEventListener<T>): void;
        hasListener(listener: IEventListener<T>): boolean;
        fireEvent(args: T): void;
        listenerCallback: IListenerCallback<T>;
    }
    class Timer {
        private func;
        private token;
        private repeat;
        private action;
        constructor(func: {
            (): void;
        });
        start(delay: number, repeat: boolean): void;
        stop(): void;
        readonly Started: boolean;
    }
    interface IEventListener<T> {
        (args: T): void;
    }
    class EventQueue {
        private static instance;
        static readonly Instance: EventQueue;
        private queue;
        private timer;
        constructor();
        invokeLater(task: {
            (): void;
        }): void;
        invokePrior(task: {
            (): void;
        }): void;
    }
    class RunOnce {
        private func;
        private scheduled;
        constructor(func: IRunnable);
        run(): void;
    }
    class ParentChangedEventArgs extends EventArgs {
        newParent: ALayout;
        sender: Object;
        constructor(newParent: ALayout, sender: Object);
    }
}
declare namespace cubee {
    interface IChangeListener {
        (sender?: Object): void;
    }
    interface IObservable {
        addChangeListener(listener: IChangeListener): void;
        removeChangeListener(listener: IChangeListener): void;
        hasChangeListener(listener: IChangeListener): void;
    }
    interface IBindable<T> {
        bind(source: T): void;
        unbind(): void;
        isBound(): boolean;
    }
    interface IAnimateable<T> {
        animate(pos: number, startValue: T, endValue: T): T;
    }
    interface IProperty<T> extends IObservable {
        getObjectValue(): Object;
        invalidate(): void;
    }
    interface IValidator<T> {
        validate(value: T): T;
    }
    class Property<T> implements IProperty<T>, IAnimateable<T>, IBindable<IProperty<T>> {
        private _value;
        private _nullable;
        private _readonly;
        private _validator;
        private static _nextId;
        private _changeListeners;
        private _valid;
        private _bindingSource;
        private _readonlyBind;
        private _bidirectionalBindProperty;
        private _bidirectionalChangeListenerThis;
        private _bidirectionalChangeListenerOther;
        private _id;
        private bindListener;
        constructor(_value?: T, _nullable?: boolean, _readonly?: boolean, _validator?: IValidator<T>);
        readonly id: string;
        readonly valid: boolean;
        value: T;
        readonly nullable: boolean;
        readonly readonly: boolean;
        initReadonlyBind(readonlyBind: IProperty<T>): void;
        private get();
        private set(newValue);
        invalidate(): void;
        invalidateIfNeeded(): void;
        fireChangeListeners(): void;
        getObjectValue(): Object;
        addChangeListener(listener: IChangeListener): void;
        removeChangeListener(listener: IChangeListener): void;
        hasChangeListener(listener: IChangeListener): boolean;
        animate(pos: number, startValue: T, endValue: T): T;
        bind(source: IProperty<T>): void;
        bidirectionalBind(other: Property<T>): void;
        unbind(): void;
        unbindTargets(): void;
        isBound(): boolean;
        isBidirectionalBound(): boolean;
        createPropertyLine(keyFrames: KeyFrame<T>[]): PropertyLine<T>;
        destroy(): void;
    }
    class Expression<T> implements IProperty<T>, IObservable {
        private _notifyListenersOnce;
        private _bindingSources;
        private _bindingListener;
        private _changeListeners;
        private _func;
        private _valid;
        private _value;
        constructor(func: {
            (): T;
        }, ...activators: IProperty<any>[]);
        readonly value: T;
        addChangeListener(listener: IChangeListener): void;
        removeChangeListener(listener: IChangeListener): void;
        hasChangeListener(listener: IChangeListener): boolean;
        getObjectValue(): T;
        bind(...properties: IProperty<any>[]): void;
        unbindAll(): void;
        unbind(property: IProperty<any>): void;
        invalidate(): void;
        invalidateIfNeeded(): void;
        private fireChangeListeners();
    }
    class KeyFrame<T> {
        private _time;
        private _property;
        private _endValue;
        private _keyframeReachedListener;
        private _interpolator;
        constructor(_time: number, _property: Property<T>, _endValue: T, _keyframeReachedListener?: {
            (): void;
        }, _interpolator?: IInterpolator);
        readonly time: number;
        readonly property: Property<T>;
        readonly endValue: T;
        readonly interpolator: IInterpolator;
        readonly keyFrameReachedListener: () => void;
    }
    class PropertyLine<T> {
        private _keyFrames;
        private _property;
        private _startTime;
        private _lastRunTime;
        private _previousFrame;
        constructor(_keyFrames: KeyFrame<T>[]);
        startTime: number;
        animate(): boolean;
    }
    interface IInterpolator {
        (value: number): number;
    }
    class Interpolators {
        static readonly Linear: IInterpolator;
    }
    abstract class AAnimator {
        private static animators;
        private static ANIMATOR_TASK;
        private started;
        static animate(): void;
        start(): void;
        stop(): void;
        readonly Started: boolean;
        readonly Stopped: boolean;
        protected abstract onAnimate(): void;
    }
    class Timeline extends AAnimator {
        private keyFrames;
        private propertyLines;
        private repeatCount;
        private finishedEvent;
        constructor(keyFrames: KeyFrame<any>[]);
        createPropertyLines(): void;
        start(repeatCount?: number): void;
        stop(): void;
        onAnimate(): void;
        onFinishedEvent(): Event<TimelineFinishedEventArgs>;
    }
    class TimelineFinishedEventArgs {
        private stopped;
        constructor(stopped?: boolean);
        readonly Stopped: boolean;
    }
    class NumberProperty extends Property<number> {
        animate(pos: number, startValue: number, endValue: number): number;
    }
    class StringProperty extends Property<string> {
    }
    class PaddingProperty extends Property<Padding> {
    }
    class BorderProperty extends Property<Border> {
    }
    class BackgroundProperty extends Property<ABackground> {
    }
    class BooleanProperty extends Property<boolean> {
    }
    class ColorProperty extends Property<Color> {
    }
}
declare namespace cubee {
    interface IStyle {
        apply(element: HTMLElement): void;
    }
    abstract class ABackground implements IStyle {
        abstract apply(element: HTMLElement): void;
    }
    class Color {
        private static _TRANSPARENT;
        static readonly TRANSPARENT: Color;
        private static _WHITE;
        static readonly WHITE: Color;
        private static _BLACK;
        static readonly BLACK: Color;
        private static _LIGHT_GRAY;
        static readonly LIGHT_GRAY: Color;
        static getArgbColor(argb: number): Color;
        static getArgbColorByComponents(alpha: number, red: number, green: number, blue: number): Color;
        static getRgbColor(rgb: number): Color;
        static getRgbColorByComponents(red: number, green: number, blue: number): Color;
        private static fixComponent(component);
        static fadeColors(startColor: Color, endColor: Color, fadePosition: number): Color;
        private static mixComponent(startValue, endValue, pos);
        private _argb;
        constructor(argb: number);
        readonly argb: number;
        readonly alpha: number;
        readonly red: number;
        readonly green: number;
        readonly blue: number;
        fade(fadeColor: Color, fadePosition: number): Color;
        toCSS(): string;
    }
    class ColorBackground extends ABackground {
        private _color;
        private _cache;
        constructor(color: Color);
        readonly color: Color;
        apply(element: HTMLElement): void;
    }
    class Padding implements IStyle {
        private _left;
        private _top;
        private _right;
        private _bottom;
        static create(padding: number): Padding;
        constructor(_left: number, _top: number, _right: number, _bottom: number);
        readonly left: number;
        readonly top: number;
        readonly right: number;
        readonly bottom: number;
        apply(element: HTMLElement): void;
    }
    class Border implements IStyle {
        private _leftWidth;
        private _topWidth;
        private _rightWidth;
        private _bottomWidth;
        private _leftColor;
        private _topColor;
        private _rightColor;
        private _bottomColor;
        private _topLeftRadius;
        private _topRightRadius;
        private _bottomLeftRadius;
        private _bottomRightRadius;
        static create(width: number, color: Color, radius: number): Border;
        constructor(_leftWidth: number, _topWidth: number, _rightWidth: number, _bottomWidth: number, _leftColor: Color, _topColor: Color, _rightColor: Color, _bottomColor: Color, _topLeftRadius: number, _topRightRadius: number, _bottomLeftRadius: number, _bottomRightRadius: number);
        readonly leftWidth: number;
        readonly topWidth: number;
        readonly rightWidth: number;
        readonly bottomWidth: number;
        readonly leftColor: Color;
        readonly topColor: Color;
        readonly rightColor: Color;
        readonly bottomColor: Color;
        readonly topLeftRadius: number;
        readonly topRightRadius: number;
        readonly bottomLeftRadius: number;
        readonly bottomRightRadius: number;
        apply(element: HTMLElement): void;
    }
    class BoxShadow implements IStyle {
        private _hPos;
        private _vPos;
        private _blur;
        private _spread;
        private _color;
        private _inner;
        constructor(_hPos: number, _vPos: number, _blur: number, _spread: number, _color: Color, _inner: boolean);
        readonly hPos: number;
        readonly vPos: number;
        readonly blur: number;
        readonly spread: number;
        readonly color: Color;
        readonly inner: boolean;
        apply(element: HTMLElement): void;
    }
    class ETextOverflow implements IStyle {
        private _css;
        private static _CLIP;
        private static _ELLIPSIS;
        static readonly CLIP: ETextOverflow;
        static readonly ELLIPSIS: ETextOverflow;
        constructor(_css: string);
        readonly CSS: string;
        apply(element: HTMLElement): void;
    }
    class ETextAlign implements IStyle {
        private _css;
        private static _LEFT;
        private static _CENTER;
        private static _RIGHT;
        private static _JUSTIFY;
        static readonly LEFT: ETextAlign;
        static readonly CENTER: ETextAlign;
        static readonly RIGHT: ETextAlign;
        static readonly JUSTIFY: ETextAlign;
        constructor(_css: string);
        readonly CSS: string;
        apply(element: HTMLElement): void;
    }
    class EHAlign {
        private _css;
        private static _LEFT;
        private static _CENTER;
        private static _RIGHT;
        static readonly LEFT: EHAlign;
        static readonly CENTER: EHAlign;
        static readonly RIGHT: EHAlign;
        constructor(_css: string);
        readonly CSS: string;
    }
    class EVAlign {
        private _css;
        private static _TOP;
        private static _MIDDLE;
        private static _BOTTOM;
        static readonly TOP: EVAlign;
        static readonly MIDDLE: EVAlign;
        static readonly BOTTOM: EVAlign;
        constructor(_css: string);
        readonly CSS: string;
    }
    class FontFamily implements IStyle {
        private _css;
        private static _arial;
        static readonly Arial: FontFamily;
        private static initialized;
        private static initFontContainerStyle();
        static registerFont(name: string, src: string, extra: string): void;
        constructor(_css: string);
        readonly CSS: string;
        apply(element: HTMLElement): void;
    }
    class ECursor {
        private _css;
        private static auto;
        static readonly AUTO: ECursor;
        constructor(_css: string);
        readonly css: string;
    }
    enum EScrollBarPolicy {
        VISIBLE = 0,
        AUTO = 1,
        HIDDEN = 2,
    }
    enum EPictureSizeMode {
        NORMAL = 0,
        CENTER = 1,
        STRETCH = 2,
        FILL = 3,
        ZOOM = 4,
        FIT_WIDTH = 5,
        FIT_HEIGHT = 6,
    }
    class Image implements IStyle {
        private _url;
        private _onLoad;
        private _width;
        private _height;
        private _loaded;
        constructor(_url: string);
        readonly url: string;
        readonly onLoad: Event<EventArgs>;
        readonly width: number;
        readonly height: number;
        readonly loaded: boolean;
        apply(element: HTMLElement): void;
    }
}
declare namespace cubee {
    function call<$P, $R>(url: string, method: string, param: $P, callback: RpcResult<$R>): void;
    interface RpcResult<$R> {
        (status: number, result: $R): void;
    }
}
declare namespace cubee {
    class LayoutChildren {
        private parent;
        private children;
        constructor(parent: ALayout);
        add(component: AComponent): void;
        insert(index: number, component: AComponent): void;
        removeComponent(component: AComponent): void;
        removeIndex(index: number): void;
        clear(): void;
        get(index: number): AComponent;
        indexOf(component: AComponent): number;
        size(): number;
    }
}
declare namespace cubee {
    class MouseEventTypes {
        static MOUSE_DOWN: number;
        static MOUSE_MOVE: number;
        static MOUSE_UP: number;
        static MOUSE_ENTER: number;
        static MOUSE_LEAVE: number;
        static MOUSE_WHEEL: number;
        constructor();
    }
    abstract class AComponent {
        private _translateX;
        private _translateY;
        private _rotate;
        private _scaleX;
        private _scaleY;
        private _transformCenterX;
        private _transformCenterY;
        private _padding;
        private _border;
        private _measuredWidth;
        private _measuredHeight;
        private _clientWidth;
        private _clientHeight;
        private _boundsWidth;
        private _boundsHeight;
        private _boundsLeft;
        private _boundsTop;
        private _measuredWidthSetter;
        private _measuredHeightSetter;
        private _clientWidthSetter;
        private _clientHeightSetter;
        private _boundsWidthSetter;
        private _boundsHeightSetter;
        private _boundsLeftSetter;
        private _boundsTopSetter;
        private _cursor;
        private _pointerTransparent;
        private _handlePointer;
        private _visible;
        private _enabled;
        private _alpha;
        private _selectable;
        private _minWidth;
        private _minHeight;
        private _maxWidth;
        private _maxHeight;
        private _hovered;
        private _hoveredSetter;
        private _pressed;
        private _pressedSetter;
        private _onClick;
        private _onMouseDown;
        private _onMouseDrag;
        private _onMouseMove;
        private _onMouseUp;
        private _onMouseEnter;
        private _onMouseLeave;
        private _onMouseWheel;
        private _onKeyDown;
        private _onKeyPress;
        private _onKeyUp;
        private _onParentChanged;
        private _onContextMenu;
        private _left;
        private _top;
        private _element;
        private _parent;
        _needsLayout: boolean;
        private _cubeePanel;
        private _transformChangedListener;
        private _postConstructRunOnce;
        constructor(rootElement: HTMLElement);
        private getClassName();
        private invokePostConstruct();
        protected postConstruct(): void;
        setCubeePanel(cubeePanel: CubeePanel): void;
        getCubeePanel(): CubeePanel;
        private updateTransform();
        requestLayout(): void;
        measure(): void;
        private onMeasure();
        scalePoint(centerX: number, centerY: number, pointX: number, pointY: number, scaleX: number, scaleY: number): Point2D;
        private rotatePoint(cx, cy, x, y, angle);
        readonly element: HTMLElement;
        readonly parent: ALayout;
        _setParent(parent: ALayout): void;
        layout(): void;
        readonly needsLayout: boolean;
        readonly TranslateX: NumberProperty;
        translateX: number;
        readonly TranslateY: NumberProperty;
        translateY: number;
        protected paddingProperty(): PaddingProperty;
        protected readonly Padding: PaddingProperty;
        protected padding: Padding;
        protected borderProperty(): BorderProperty;
        protected readonly Border: BorderProperty;
        protected border: Border;
        readonly MeasuredWidth: NumberProperty;
        measuredWidth: number;
        readonly MeasuredHeight: NumberProperty;
        measuredHeight: number;
        readonly ClientWidth: NumberProperty;
        clientWidth: number;
        readonly ClientHeight: NumberProperty;
        clientHeight: number;
        readonly BoundsWidth: NumberProperty;
        boundsWidth: number;
        readonly BoundsHeight: NumberProperty;
        boundsHeight: number;
        readonly BoundsLeft: NumberProperty;
        boundsLeft: number;
        readonly BoundsTop: NumberProperty;
        boundsTop: number;
        protected minWidthProperty(): NumberProperty;
        protected readonly MinWidth: NumberProperty;
        protected minWidth: number;
        protected minHeightProperty(): NumberProperty;
        protected readonly MinHeight: NumberProperty;
        protected minHeight: number;
        protected maxWidthProperty(): NumberProperty;
        protected readonly MaxWidth: NumberProperty;
        protected maxWidth: number;
        protected maxHeightProperty(): NumberProperty;
        protected readonly MaxHeight: NumberProperty;
        protected maxHeight: number;
        protected setPosition(left: number, top: number): void;
        _setLeft(left: number): void;
        _setTop(top: number): void;
        protected setSize(width: number, height: number): void;
        readonly Cursor: Property<ECursor>;
        cursor: ECursor;
        readonly PointerTransparent: Property<boolean>;
        pointerTransparent: boolean;
        readonly Visible: Property<boolean>;
        visible: boolean;
        readonly onClick: Event<MouseEvent>;
        readonly onContextMenu: Event<Object>;
        readonly onMouseDown: Event<MouseEvent>;
        readonly onMouseMove: Event<MouseEvent>;
        readonly onMouseUp: Event<MouseEvent>;
        readonly onMouseEnter: Event<MouseEvent>;
        readonly onMouseLeave: Event<MouseEvent>;
        readonly onMouseWheel: Event<MouseEvent>;
        readonly onKeyDown: Event<KeyboardEvent>;
        readonly onKeyPress: Event<KeyboardEvent>;
        readonly onKeyUp: Event<KeyboardEvent>;
        readonly onParentChanged: Event<ParentChangedEventArgs>;
        readonly Alpha: NumberProperty;
        alpha: number;
        readonly HandlePointer: Property<boolean>;
        handlePointer: boolean;
        readonly Enabled: Property<boolean>;
        enabled: boolean;
        readonly Selectable: Property<boolean>;
        selectable: boolean;
        readonly left: number;
        readonly top: number;
        readonly Rotate: NumberProperty;
        rotate: number;
        readonly ScaleX: NumberProperty;
        scaleX: number;
        readonly ScaleY: NumberProperty;
        scaleY: number;
        readonly TransformCenterX: NumberProperty;
        transformCenterX: number;
        readonly TransformCenterY: NumberProperty;
        transformCenterY: number;
        readonly Hovered: Property<boolean>;
        hovered: boolean;
        readonly Pressed: Property<boolean>;
        pressed: boolean;
    }
}
declare namespace cubee {
    abstract class ALayout extends AComponent {
        private _children;
        constructor(element: HTMLElement);
        protected readonly children_inner: LayoutChildren;
        abstract _onChildAdded(child: AComponent): void;
        abstract _onChildRemoved(child: AComponent, index: number): void;
        abstract _onChildrenCleared(): void;
        layout(): void;
        protected abstract onLayout(): void;
        getComponentsAtPosition(x: number, y: number): AComponent[];
        private getComponentsAtPosition_impl(root, x, y, result);
        protected setChildLeft(child: AComponent, left: number): void;
        protected setChildTop(child: AComponent, top: number): void;
    }
}
declare namespace cubee {
    abstract class AUserControl extends ALayout {
        private _width;
        private _height;
        private _background;
        private _shadow;
        private _draggable;
        constructor();
        protected widthProperty(): NumberProperty;
        protected readonly Width: NumberProperty;
        protected width: number;
        protected heightProperty(): NumberProperty;
        protected readonly Height: NumberProperty;
        protected height: number;
        protected backgroundProperty(): BackgroundProperty;
        protected readonly Background: BackgroundProperty;
        protected background: ABackground;
        protected shadowProperty(): Property<BoxShadow>;
        protected readonly Shadow: Property<BoxShadow>;
        protected shadow: BoxShadow;
        readonly Draggable: BooleanProperty;
        draggable: boolean;
        _onChildAdded(child: AComponent): void;
        _onChildRemoved(child: AComponent, index: number): void;
        _onChildrenCleared(): void;
        protected onLayout(): void;
    }
}
declare namespace cubee {
    class AView<T> extends AUserControl {
        private _model;
        constructor(_model: T);
        readonly model: T;
    }
}
declare namespace cubee {
    class Panel extends AUserControl {
        protected widthProperty(): NumberProperty;
        readonly Width: NumberProperty;
        width: number;
        protected heightProperty(): NumberProperty;
        readonly Height: NumberProperty;
        height: number;
        protected backgroundProperty(): BackgroundProperty;
        readonly Background: BackgroundProperty;
        background: ABackground;
        protected shadowProperty(): Property<BoxShadow>;
        readonly Shadow: Property<BoxShadow>;
        shadow: BoxShadow;
        readonly children: LayoutChildren;
    }
}
declare namespace cubee {
    class HBox extends ALayout {
        private _height;
        private _cellWidths;
        private _hAligns;
        private _vAligns;
        constructor();
        setCellWidth(indexOrComponent: number | AComponent, cellHeight: number): void;
        getCellWidth(indexOrComponent: number | AComponent): number;
        setCellHAlign(indexOrComponent: number | AComponent, hAlign: EHAlign): void;
        getCellHAlign(indexOrComponent: number | AComponent): EHAlign;
        setCellVAlign(indexOrComponent: number | AComponent, vAlign: EVAlign): void;
        getCellVAlign(indexOrComponent: number | AComponent): EVAlign;
        setLastCellHAlign(hAlign: EHAlign): void;
        setLastCellVAlign(vAlign: EVAlign): void;
        setLastCellWidth(width: number): void;
        addEmptyCell(width: number): void;
        _onChildAdded(child: AComponent): void;
        _onChildRemoved(child: AComponent, index: number): void;
        _onChildrenCleared(): void;
        protected onLayout(): void;
        private setInList<T>(list, index, value);
        private getFromList<T>(list, index);
        private removeFromList<T>(list, index);
        readonly children: LayoutChildren;
        readonly Height: NumberProperty;
        height: number;
    }
}
declare namespace cubee {
    class VBox extends ALayout {
        private _width;
        private _cellHeights;
        private _hAligns;
        private _vAligns;
        constructor();
        readonly children: LayoutChildren;
        setCellHeight(indexOrComponent: number | AComponent, cellHeight: number): void;
        private setInList<T>(list, index, value);
        private getFromList<T>(list, index);
        private removeFromList<T>(list, index);
        getCellHeight(indexOrComponent: number | AComponent): number;
        setCellHAlign(indexOrComponent: number | AComponent, hAlign: EHAlign): void;
        getCellHAlign(indexOrComponent: number | AComponent): EHAlign;
        setCellVAlign(indexOrComponent: number | AComponent, vAlign: EVAlign): void;
        getCellVAlign(indexOrComponent: number | AComponent): EVAlign;
        setLastCellHAlign(hAlign: EHAlign): void;
        setLastCellVAlign(vAlign: EVAlign): void;
        setLastCellHeight(height: number): void;
        addEmptyCell(height: number): void;
        readonly Width: NumberProperty;
        width: number;
        _onChildAdded(child: AComponent): void;
        _onChildRemoved(child: AComponent, index: number): void;
        _onChildrenCleared(): void;
        protected onLayout(): void;
    }
}
declare namespace cubee {
    class ScrollBox extends AUserControl {
        private _content;
        private _hScrollPolicy;
        private _vScrollPolicy;
        private _scrollWidth;
        private _scrollHeight;
        private _hScrollPos;
        private _vScrollPos;
        private _maxHScrollPos;
        private _maxVScrollPos;
        private _maxHScrollPosWriter;
        private _maxVScrollPosWriter;
        private _calculateScrollWidthExp;
        private _calculateScrollHeightExp;
        constructor();
        protected widthProperty(): NumberProperty;
        readonly Width: NumberProperty;
        width: number;
        protected heightProperty(): NumberProperty;
        readonly Height: NumberProperty;
        height: number;
        readonly Content: Property<AComponent>;
        content: AComponent;
        readonly HScrollPolicy: Property<EScrollBarPolicy>;
        hScrollPolicy: EScrollBarPolicy;
        readonly VScrollPolicy: Property<EScrollBarPolicy>;
        vScrollPolicy: EScrollBarPolicy;
        readonly ScrollWidth: NumberProperty;
        scrollWidth: number;
        readonly ScrollHeight: NumberProperty;
        scrollHeight: number;
        readonly HScrollPos: NumberProperty;
        hScrollPos: number;
        readonly VScrollPos: NumberProperty;
        vScrollPos: number;
        readonly MaxHScrollPos: NumberProperty;
        maxHScrollPos: number;
        readonly MaxVScrollPos: NumberProperty;
        maxVScrollPos: number;
    }
}
declare namespace cubee {
    class Label extends AComponent {
        private _width;
        private _height;
        private _text;
        private _textOverflow;
        private _foreColor;
        private _textAlign;
        private _verticalAlign;
        private _italic;
        private _underline;
        private _fontSize;
        private _fontFamily;
        private _fontWeight;
        constructor();
        readonly Width: NumberProperty;
        width: number;
        readonly Height: NumberProperty;
        height: number;
        readonly Text: StringProperty;
        text: string;
        readonly TextOverflow: Property<ETextOverflow>;
        textOverflow: ETextOverflow;
        readonly ForeColor: ColorProperty;
        foreColor: Color;
        readonly VerticalAlign: Property<EVAlign>;
        verticalAlign: EVAlign;
        readonly FontWeight: Property<number>;
        fontWeight: number;
        readonly Italic: BooleanProperty;
        italic: boolean;
        readonly Underline: BooleanProperty;
        underline: boolean;
        readonly TextAlign: Property<ETextAlign>;
        textAlign: ETextAlign;
        readonly FontSize: NumberProperty;
        fontSize: number;
        readonly FontFamily: Property<FontFamily>;
        fontFamily: FontFamily;
    }
}
declare namespace cubee {
    class Button extends AComponent {
        private _width;
        private _height;
        private _text;
        private _textOverflow;
        private _foreColor;
        private _textAlign;
        private _verticalAlign;
        private _bold;
        private _italic;
        private _underline;
        private _fontSize;
        private _fontFamily;
        private _background;
        private _shadow;
        constructor();
        readonly Width: NumberProperty;
        width: number;
        readonly Height: NumberProperty;
        height: number;
        readonly Text: StringProperty;
        text: string;
        readonly TextOverflow: Property<ETextOverflow>;
        textOverflow: ETextOverflow;
        readonly ForeColor: ColorProperty;
        foreColor: Color;
        readonly VerticalAlign: Property<EVAlign>;
        verticalAlign: EVAlign;
        readonly Bold: BooleanProperty;
        bold: boolean;
        readonly Italic: BooleanProperty;
        italic: boolean;
        readonly Underline: BooleanProperty;
        underline: boolean;
        readonly TextAlign: Property<ETextAlign>;
        textAlign: ETextAlign;
        readonly FontSize: NumberProperty;
        fontSize: number;
        readonly FontFamily: Property<FontFamily>;
        fontFamily: FontFamily;
        readonly Background: BackgroundProperty;
        background: ABackground;
        readonly Shadow: Property<BoxShadow>;
        shadow: BoxShadow;
    }
}
declare namespace cubee {
    class TextBox extends AComponent {
        private _width;
        private _height;
        private _text;
        private _background;
        private _foreColor;
        private _textAlign;
        private _verticalAlign;
        private _bold;
        private _italic;
        private _underline;
        private _fontSize;
        private _fontFamily;
        private _placeholder;
        constructor();
        readonly Width: NumberProperty;
        width: number;
        readonly Height: NumberProperty;
        height: number;
        readonly Text: StringProperty;
        text: string;
        readonly Background: BackgroundProperty;
        background: ABackground;
        readonly ForeColor: ColorProperty;
        foreColor: Color;
        readonly TextAlign: Property<ETextAlign>;
        textAlign: ETextAlign;
        readonly VerticalAlign: Property<EVAlign>;
        verticalAlign: EVAlign;
        readonly Bold: BooleanProperty;
        bold: boolean;
        readonly Italic: BooleanProperty;
        italic: boolean;
        readonly Underline: BooleanProperty;
        underline: boolean;
        readonly FontSize: NumberProperty;
        fontSize: number;
        readonly FontFamily: Property<FontFamily>;
        fontFamily: FontFamily;
        readonly Placeholder: StringProperty;
        placeholder: string;
    }
}
declare namespace cubee {
    class PasswordBox extends AComponent {
        private _width;
        private _height;
        private _text;
        private _background;
        private _foreColor;
        private _textAlign;
        private _verticalAlign;
        private _bold;
        private _italic;
        private _underline;
        private _fontSize;
        private _fontFamily;
        private _placeholder;
        constructor();
        readonly Width: NumberProperty;
        width: number;
        readonly Height: NumberProperty;
        height: number;
        readonly Text: StringProperty;
        text: string;
        readonly Background: BackgroundProperty;
        background: ABackground;
        readonly ForeColor: ColorProperty;
        foreColor: Color;
        readonly TextAlign: Property<ETextAlign>;
        textAlign: ETextAlign;
        readonly VerticalAlign: Property<EVAlign>;
        verticalAlign: EVAlign;
        readonly Bold: BooleanProperty;
        bold: boolean;
        readonly Italic: BooleanProperty;
        italic: boolean;
        readonly Underline: BooleanProperty;
        underline: boolean;
        readonly FontSize: NumberProperty;
        fontSize: number;
        readonly FontFamily: Property<FontFamily>;
        fontFamily: FontFamily;
        readonly Placeholder: StringProperty;
        placeholder: string;
    }
}
declare namespace cubee {
    class TextArea extends AComponent {
        private _width;
        private _height;
        private _text;
        private _background;
        private _foreColor;
        private _textAlign;
        private _verticalAlign;
        private _bold;
        private _italic;
        private _underline;
        private _fontSize;
        private _fontFamily;
        private _placeholder;
        constructor();
        readonly Width: NumberProperty;
        width: number;
        readonly Height: NumberProperty;
        height: number;
        readonly Text: StringProperty;
        text: string;
        readonly Background: BackgroundProperty;
        background: ABackground;
        readonly ForeColor: ColorProperty;
        foreColor: Color;
        readonly TextAlign: Property<ETextAlign>;
        textAlign: ETextAlign;
        readonly VerticalAlign: Property<EVAlign>;
        verticalAlign: EVAlign;
        readonly Bold: BooleanProperty;
        bold: boolean;
        readonly Italic: BooleanProperty;
        italic: boolean;
        readonly Underline: BooleanProperty;
        underline: boolean;
        readonly FontSize: NumberProperty;
        fontSize: number;
        readonly FontFamily: Property<FontFamily>;
        fontFamily: FontFamily;
        readonly Placeholder: StringProperty;
        placeholder: string;
    }
}
declare namespace cubee {
    class CheckBox extends AComponent {
        private _checked;
        constructor();
        readonly Checked: BooleanProperty;
        checked: boolean;
    }
}
declare namespace cubee {
    class ComboBox<T> extends AComponent {
        private _selectedIndex;
        private _selectedItem;
        private items;
        private _width;
        private _height;
        private _text;
        private _background;
        private _foreColor;
        private _textAlign;
        private _verticalAlign;
        private _bold;
        private _italic;
        private _underline;
        private _fontSize;
        private _fontFamily;
        private _placeholder;
        constructor();
        readonly Width: NumberProperty;
        width: number;
        readonly Height: NumberProperty;
        height: number;
        readonly Text: StringProperty;
        text: string;
        readonly Background: BackgroundProperty;
        background: ABackground;
        readonly ForeColor: ColorProperty;
        foreColor: Color;
        readonly TextAlign: Property<ETextAlign>;
        textAlign: ETextAlign;
        readonly VerticalAlign: Property<EVAlign>;
        verticalAlign: EVAlign;
        readonly Bold: BooleanProperty;
        bold: boolean;
        readonly Italic: BooleanProperty;
        italic: boolean;
        readonly Underline: BooleanProperty;
        underline: boolean;
        readonly FontSize: NumberProperty;
        fontSize: number;
        readonly FontFamily: Property<FontFamily>;
        fontFamily: FontFamily;
        readonly Placeholder: StringProperty;
        placeholder: string;
        protected selectedIndexProperty(): NumberProperty;
        readonly SelectedIndex: NumberProperty;
        selectedIndex: number;
        protected selectedItemProperty(): Property<T>;
        readonly SelectedItem: Property<T>;
        selectedItem: T;
    }
}
declare namespace cubee {
    class PictureBox extends AComponent {
        private _width;
        private _height;
        private _pictureSizeMode;
        private _image;
        private _background;
        private _imgElement;
        constructor();
        private recalculateSize();
        protected pictureSizeModeProperty(): Property<EPictureSizeMode>;
        readonly PictureSizeMode: Property<EPictureSizeMode>;
        pictureSizeMode: EPictureSizeMode;
        protected widthProperty(): NumberProperty;
        readonly Width: NumberProperty;
        width: number;
        protected heightProperty(): NumberProperty;
        readonly Height: NumberProperty;
        height: number;
        protected paddingProperty(): PaddingProperty;
        readonly Padding: PaddingProperty;
        padding: Padding;
        protected borderProperty(): BorderProperty;
        readonly Border: BorderProperty;
        border: Border;
        protected backgroundProperty(): BackgroundProperty;
        readonly Background: BackgroundProperty;
        background: ABackground;
        protected imageProperty(): Property<Image>;
        readonly Image: Property<Image>;
        image: Image;
    }
}
declare namespace cubee {
    class FAIcon extends AUserControl {
        private static _initialized;
        private static initFA();
        private _size;
        private _color;
        private _spin;
        private _icon;
        private _iElement;
        private _changeListener;
        constructor(icon: EIcon);
        private refreshStyle();
        protected colorProperty(): ColorProperty;
        readonly Color: ColorProperty;
        color: Color;
        protected sizeProperty(): NumberProperty;
        readonly Size: NumberProperty;
        size: number;
        protected spinProperty(): BooleanProperty;
        readonly Spin: BooleanProperty;
        spin: boolean;
        protected iconProperty(): Property<EIcon>;
        readonly Icon: Property<EIcon>;
        icon: EIcon;
    }
}
declare namespace cubee {
    class EIcon {
        private _value;
        private static __500PX;
        static readonly _500PX: EIcon;
        private static _AMAZON;
        static readonly AMAZON: EIcon;
        private static _BALANCE_SCALE;
        static readonly BALANCE_SCALE: EIcon;
        private static _BATTERY_0;
        static readonly BATTERY_0: EIcon;
        private static _BATTERY_1;
        static readonly BATTERY_1: EIcon;
        private static _BATTERY_2;
        static readonly BATTERY_2: EIcon;
        private static _BATTERY_3;
        static readonly BATTERY_3: EIcon;
        private static _BATTERY_4;
        static readonly BATTERY_4: EIcon;
        private static _BATTERY_EMPTY;
        static readonly BATTERY_EMPTY: EIcon;
        private static _BATTERY_FULL;
        static readonly BATTERY_FULL: EIcon;
        private static _BATTERY_HALF;
        static readonly BATTERY_HALF: EIcon;
        private static _BATTERY_QUARTER;
        static readonly BATTERY_QUARTER: EIcon;
        private static _BATTERY_THREE_QUARTERS;
        static readonly BATTERY_THREE_QUARTERS: EIcon;
        private static _BLACK_TIE;
        static readonly BLACK_TIE: EIcon;
        private static _CALENDAR_CHECK_O;
        static readonly CALENDAR_CHECK_O: EIcon;
        private static _CALENDAR_MINUS_O;
        static readonly CALENDAR_MINUS_O: EIcon;
        private static _CALENDAR_PLUS_O;
        static readonly CALENDAR_PLUS_O: EIcon;
        private static _CALENDAR_TIMES_O;
        static readonly CALENDAR_TIMES_O: EIcon;
        private static _CC_DINERS_CLUB;
        static readonly CC_DINERS_CLUB: EIcon;
        private static _CC_JCB;
        static readonly CC_JCB: EIcon;
        private static _CHROME;
        static readonly CHROME: EIcon;
        private static _CLONE;
        static readonly CLONE: EIcon;
        private static _COMMENTING;
        static readonly COMMENTING: EIcon;
        private static _COMMENTING_O;
        static readonly COMMENTING_O: EIcon;
        private static _CONTAO;
        static readonly CONTAO: EIcon;
        private static _CREATIVE_COMMONS;
        static readonly CREATIVE_COMMONS: EIcon;
        private static _EXPEDITEDSSL;
        static readonly EXPEDITEDSSL: EIcon;
        private static _FIREFOX;
        static readonly FIREFOX: EIcon;
        private static _FONTICONS;
        static readonly FONTICONS: EIcon;
        private static _GENDERLESS;
        static readonly GENDERLESS: EIcon;
        private static _GET_POCKET;
        static readonly GET_POCKET: EIcon;
        private static _GG;
        static readonly GG: EIcon;
        private static _GG_CIRCLE;
        static readonly GG_CIRCLE: EIcon;
        private static _HAND_GRAB_O;
        static readonly HAND_GRAB_O: EIcon;
        private static _HAND_LIZARD_O;
        static readonly HAND_LIZARD_O: EIcon;
        private static _HAND_PAPER_O;
        static readonly HAND_PAPER_O: EIcon;
        private static _HAND_PEACE_O;
        static readonly HAND_PEACE_O: EIcon;
        private static _HAND_POINTER_O;
        static readonly HAND_POINTER_O: EIcon;
        private static _HAND_ROCK_O;
        static readonly HAND_ROCK_O: EIcon;
        private static _HAND_SCISSORS_O;
        static readonly HAND_SCISSORS_O: EIcon;
        private static _HAND_SPOCK_O;
        static readonly HAND_SPOCK_O: EIcon;
        private static _HAND_STOP_O;
        static readonly HAND_STOP_O: EIcon;
        private static _HOURGLASS;
        static readonly HOURGLASS: EIcon;
        private static _HOURGLASS_1;
        static readonly HOURGLASS_1: EIcon;
        private static _HOURGLASS_2;
        static readonly HOURGLASS_2: EIcon;
        private static _HOURGLASS_3;
        static readonly HOURGLASS_3: EIcon;
        private static _HOURGLASS_END;
        static readonly HOURGLASS_END: EIcon;
        private static _HOURGLASS_HALF;
        static readonly HOURGLASS_HALF: EIcon;
        private static _HOURGLASS_O;
        static readonly HOURGLASS_O: EIcon;
        private static _HOURGLASS_START;
        static readonly HOURGLASS_START: EIcon;
        private static _HOUZZ;
        static readonly HOUZZ: EIcon;
        private static _I_CURSOR;
        static readonly I_CURSOR: EIcon;
        private static _INDUSTRY;
        static readonly INDUSTRY: EIcon;
        private static _INTERNET_EXPLORER;
        static readonly INTERNET_EXPLORER: EIcon;
        private static _MAP;
        static readonly MAP: EIcon;
        private static _MAP_O;
        static readonly MAP_O: EIcon;
        private static _MAP_PIN;
        static readonly MAP_PIN: EIcon;
        private static _MAP_SIGNS;
        static readonly MAP_SIGNS: EIcon;
        private static _MOUSE_POINTER;
        static readonly MOUSE_POINTER: EIcon;
        private static _OBJECT_GROUP;
        static readonly OBJECT_GROUP: EIcon;
        private static _OBJECT_UNGROUP;
        static readonly OBJECT_UNGROUP: EIcon;
        private static _ODNOKLASSNIKI;
        static readonly ODNOKLASSNIKI: EIcon;
        private static _ODNOKLASSNIKI_SQUARE;
        static readonly ODNOKLASSNIKI_SQUARE: EIcon;
        private static _OPENCART;
        static readonly OPENCART: EIcon;
        private static _OPERA;
        static readonly OPERA: EIcon;
        private static _OPTIN_MONSTER;
        static readonly OPTIN_MONSTER: EIcon;
        private static _REGISTERED;
        static readonly REGISTERED: EIcon;
        private static _SAFARI;
        static readonly SAFARI: EIcon;
        private static _STICKY_NOTE;
        static readonly STICKY_NOTE: EIcon;
        private static _STICKY_NOTE_O;
        static readonly STICKY_NOTE_O: EIcon;
        private static _TELEVISION;
        static readonly TELEVISION: EIcon;
        private static _TRADEMARK;
        static readonly TRADEMARK: EIcon;
        private static _TRIPADVISOR;
        static readonly TRIPADVISOR: EIcon;
        private static _TV;
        static readonly TV: EIcon;
        private static _VIMEO;
        static readonly VIMEO: EIcon;
        private static _WIKIPEDIA_W;
        static readonly WIKIPEDIA_W: EIcon;
        private static _Y_COMBINATOR;
        static readonly Y_COMBINATOR: EIcon;
        private static _YC;
        static readonly YC: EIcon;
        private static _ADJUST;
        static readonly ADJUST: EIcon;
        private static _ANCHOR;
        static readonly ANCHOR: EIcon;
        private static _ARCHIVE;
        static readonly ARCHIVE: EIcon;
        private static _AREA_CHART;
        static readonly AREA_CHART: EIcon;
        private static _ARROWS;
        static readonly ARROWS: EIcon;
        private static _ARROWS_H;
        static readonly ARROWS_H: EIcon;
        private static _ARROWS_V;
        static readonly ARROWS_V: EIcon;
        private static _ASTERISK;
        static readonly ASTERISK: EIcon;
        private static _AT;
        static readonly AT: EIcon;
        private static _AUTOMOBILE;
        static readonly AUTOMOBILE: EIcon;
        private static _BAN;
        static readonly BAN: EIcon;
        private static _BANK;
        static readonly BANK: EIcon;
        private static _BAR_CHART;
        static readonly BAR_CHART: EIcon;
        private static _BAR_CHART_O;
        static readonly BAR_CHART_O: EIcon;
        private static _BARCODE;
        static readonly BARCODE: EIcon;
        private static _BARS;
        static readonly BARS: EIcon;
        private static _BED;
        static readonly BED: EIcon;
        private static _BEER;
        static readonly BEER: EIcon;
        private static _BELL;
        static readonly BELL: EIcon;
        private static _BELL_O;
        static readonly BELL_O: EIcon;
        private static _BELL_SLASH;
        static readonly BELL_SLASH: EIcon;
        private static _BELL_SLASH_O;
        static readonly BELL_SLASH_O: EIcon;
        private static _BICYCLE;
        static readonly BICYCLE: EIcon;
        private static _BINOCULARS;
        static readonly BINOCULARS: EIcon;
        private static _BIRTHDAY_CAKE;
        static readonly BIRTHDAY_CAKE: EIcon;
        private static _BOLT;
        static readonly BOLT: EIcon;
        private static _BOMB;
        static readonly BOMB: EIcon;
        private static _BOOK;
        static readonly BOOK: EIcon;
        private static _BOOKMARK;
        static readonly BOOKMARK: EIcon;
        private static _BOOKMARK_O;
        static readonly BOOKMARK_O: EIcon;
        private static _BRIEFCASE;
        static readonly BRIEFCASE: EIcon;
        private static _BUG;
        static readonly BUG: EIcon;
        private static _BUILDING;
        static readonly BUILDING: EIcon;
        private static _BUILDING_O;
        static readonly BUILDING_O: EIcon;
        private static _BULLHORN;
        static readonly BULLHORN: EIcon;
        private static _BULLSEYE;
        static readonly BULLSEYE: EIcon;
        private static _BUS;
        static readonly BUS: EIcon;
        private static _CAB;
        static readonly CAB: EIcon;
        private static _CALCULATOR;
        static readonly CALCULATOR: EIcon;
        private static _CALENDAR;
        static readonly CALENDAR: EIcon;
        private static _CAMERA;
        static readonly CAMERA: EIcon;
        private static _CAMERA_RETRO;
        static readonly CAMERA_RETRO: EIcon;
        private static _CAR;
        static readonly CAR: EIcon;
        private static _CARET_SQUARE_O_DOWN;
        static readonly CARET_SQUARE_O_DOWN: EIcon;
        private static _CARET_SQUARE_O_LEFT;
        static readonly CARET_SQUARE_O_LEFT: EIcon;
        private static _CARET_SQUARE_O_RIGHT;
        static readonly CARET_SQUARE_O_RIGHT: EIcon;
        private static _CARET_SQUARE_O_UP;
        static readonly CARET_SQUARE_O_UP: EIcon;
        private static _CART_ARROW_DOWN;
        static readonly CART_ARROW_DOWN: EIcon;
        private static _CART_PLUS;
        static readonly CART_PLUS: EIcon;
        private static _CC;
        static readonly CC: EIcon;
        private static _CERTIFICATE;
        static readonly CERTIFICATE: EIcon;
        private static _CHECK;
        static readonly CHECK: EIcon;
        private static _CHECK_CIRCLE;
        static readonly CHECK_CIRCLE: EIcon;
        private static _CHECK_CIRCLE_O;
        static readonly CHECK_CIRCLE_O: EIcon;
        private static _CHECK_SQUARE;
        static readonly CHECK_SQUARE: EIcon;
        private static _CHECK_SQUARE_O;
        static readonly CHECK_SQUARE_O: EIcon;
        private static _CHILD;
        static readonly CHILD: EIcon;
        private static _CIRCLE;
        static readonly CIRCLE: EIcon;
        private static _CIRCLE_O;
        static readonly CIRCLE_O: EIcon;
        private static _CIRCLE_O_NOTCH;
        static readonly CIRCLE_O_NOTCH: EIcon;
        private static _CIRCLE_THIN;
        static readonly CIRCLE_THIN: EIcon;
        private static _CLOCK_O;
        static readonly CLOCK_O: EIcon;
        private static _CLOSE;
        static readonly CLOSE: EIcon;
        private static _CLOUD;
        static readonly CLOUD: EIcon;
        private static _CLOUD_DOWNLOAD;
        static readonly CLOUD_DOWNLOAD: EIcon;
        private static _CLOUD_UPLOAD;
        static readonly CLOUD_UPLOAD: EIcon;
        private static _CODE;
        static readonly CODE: EIcon;
        private static _CODE_FORK;
        static readonly CODE_FORK: EIcon;
        private static _COFFEE;
        static readonly COFFEE: EIcon;
        private static _COG;
        static readonly COG: EIcon;
        private static _COGS;
        static readonly COGS: EIcon;
        private static _COMMENT;
        static readonly COMMENT: EIcon;
        private static _COMMENT_O;
        static readonly COMMENT_O: EIcon;
        private static _COMMENTS;
        static readonly COMMENTS: EIcon;
        private static _COMMENTS_O;
        static readonly COMMENTS_O: EIcon;
        private static _COMPASS;
        static readonly COMPASS: EIcon;
        private static _COPYRIGHT;
        static readonly COPYRIGHT: EIcon;
        private static _CREDIT_CARD;
        static readonly CREDIT_CARD: EIcon;
        private static _CROP;
        static readonly CROP: EIcon;
        private static _CROSSHAIRS;
        static readonly CROSSHAIRS: EIcon;
        private static _CUBE;
        static readonly CUBE: EIcon;
        private static _CUBES;
        static readonly CUBES: EIcon;
        private static _CUTLERY;
        static readonly CUTLERY: EIcon;
        private static _DASHBOARD;
        static readonly DASHBOARD: EIcon;
        private static _DATABASE;
        static readonly DATABASE: EIcon;
        private static _DESKTOP;
        static readonly DESKTOP: EIcon;
        private static _DIAMOND;
        static readonly DIAMOND: EIcon;
        private static _DOT_CIRCLE_O;
        static readonly DOT_CIRCLE_O: EIcon;
        private static _DOWNLOAD;
        static readonly DOWNLOAD: EIcon;
        private static _EDIT;
        static readonly EDIT: EIcon;
        private static _ELLIPSIS_H;
        static readonly ELLIPSIS_H: EIcon;
        private static _ELLIPSIS_V;
        static readonly ELLIPSIS_V: EIcon;
        private static _ENVELOPE;
        static readonly ENVELOPE: EIcon;
        private static _ENVELOPE_O;
        static readonly ENVELOPE_O: EIcon;
        private static _ENVELOPE_SQUARE;
        static readonly ENVELOPE_SQUARE: EIcon;
        private static _ERASER;
        static readonly ERASER: EIcon;
        private static _EXCHANGE;
        static readonly EXCHANGE: EIcon;
        private static _EXCLAMATION;
        static readonly EXCLAMATION: EIcon;
        private static _EXCLAMATION_CIRCLE;
        static readonly EXCLAMATION_CIRCLE: EIcon;
        private static _EXCLAMATION_TRIANGLE;
        static readonly EXCLAMATION_TRIANGLE: EIcon;
        private static _EXTERNAL_LINK;
        static readonly EXTERNAL_LINK: EIcon;
        private static _EXTERNAL_LINK_SQUARE;
        static readonly EXTERNAL_LINK_SQUARE: EIcon;
        private static _EYE;
        static readonly EYE: EIcon;
        private static _EYE_SLASH;
        static readonly EYE_SLASH: EIcon;
        private static _EYEDROPPER;
        static readonly EYEDROPPER: EIcon;
        private static _FAX;
        static readonly FAX: EIcon;
        private static _FEED;
        static readonly FEED: EIcon;
        private static _FEMALE;
        static readonly FEMALE: EIcon;
        private static _FIGHTER_JET;
        static readonly FIGHTER_JET: EIcon;
        private static _FILE_ARCHIVE_O;
        static readonly FILE_ARCHIVE_O: EIcon;
        private static _FILE_AUDIO_O;
        static readonly FILE_AUDIO_O: EIcon;
        private static _FILE_CODE_O;
        static readonly FILE_CODE_O: EIcon;
        private static _FILE_EXCEL_O;
        static readonly FILE_EXCEL_O: EIcon;
        private static _FILE_IMAGE_O;
        static readonly FILE_IMAGE_O: EIcon;
        private static _FILE_MOVIE_O;
        static readonly FILE_MOVIE_O: EIcon;
        private static _FILE_PDF_O;
        static readonly FILE_PDF_O: EIcon;
        private static _FILE_PHOTO_O;
        static readonly FILE_PHOTO_O: EIcon;
        private static _FILE_PICTURE_O;
        static readonly FILE_PICTURE_O: EIcon;
        private static _FILE_POWERPOINT_O;
        static readonly FILE_POWERPOINT_O: EIcon;
        private static _FILE_SOUND_O;
        static readonly FILE_SOUND_O: EIcon;
        private static _FILE_VIDEO_O;
        static readonly FILE_VIDEO_O: EIcon;
        private static _FILE_WORD_O;
        static readonly FILE_WORD_O: EIcon;
        private static _FILE_ZIP_O;
        static readonly FILE_ZIP_O: EIcon;
        private static _FILM;
        static readonly FILM: EIcon;
        private static _FILTER;
        static readonly FILTER: EIcon;
        private static _FIRE;
        static readonly FIRE: EIcon;
        private static _FIRE_EXTINGUISHER;
        static readonly FIRE_EXTINGUISHER: EIcon;
        private static _FLAG;
        static readonly FLAG: EIcon;
        private static _FLAG_CHECKERED;
        static readonly FLAG_CHECKERED: EIcon;
        private static _FLAG_O;
        static readonly FLAG_O: EIcon;
        private static _FLASH;
        static readonly FLASH: EIcon;
        private static _FLASK;
        static readonly FLASK: EIcon;
        private static _FOLDER;
        static readonly FOLDER: EIcon;
        private static _FOLDER_O;
        static readonly FOLDER_O: EIcon;
        private static _FOLDER_OPEN;
        static readonly FOLDER_OPEN: EIcon;
        private static _FOLDER_OPEN_O;
        static readonly FOLDER_OPEN_O: EIcon;
        private static _FROWN_O;
        static readonly FROWN_O: EIcon;
        private static _FUTBOL_O;
        static readonly FUTBOL_O: EIcon;
        private static _GAMEPAD;
        static readonly GAMEPAD: EIcon;
        private static _GAVEL;
        static readonly GAVEL: EIcon;
        private static _GEAR;
        static readonly GEAR: EIcon;
        private static _GEARS;
        static readonly GEARS: EIcon;
        private static _GIFT;
        static readonly GIFT: EIcon;
        private static _GLASS;
        static readonly GLASS: EIcon;
        private static _GLOBE;
        static readonly GLOBE: EIcon;
        private static _GRADUATION_CAP;
        static readonly GRADUATION_CAP: EIcon;
        private static _GROUP;
        static readonly GROUP: EIcon;
        private static _HDD_O;
        static readonly HDD_O: EIcon;
        private static _HEADPHONES;
        static readonly HEADPHONES: EIcon;
        private static _HEART;
        static readonly HEART: EIcon;
        private static _HEART_O;
        static readonly HEART_O: EIcon;
        private static _HEARTBEAT;
        static readonly HEARTBEAT: EIcon;
        private static _HISTORY;
        static readonly HISTORY: EIcon;
        private static _HOME;
        static readonly HOME: EIcon;
        private static _HOTEL;
        static readonly HOTEL: EIcon;
        private static _IMAGE;
        static readonly IMAGE: EIcon;
        private static _INBOX;
        static readonly INBOX: EIcon;
        private static _INFO;
        static readonly INFO: EIcon;
        private static _INFO_CIRCLE;
        static readonly INFO_CIRCLE: EIcon;
        private static _INSTITUTION;
        static readonly INSTITUTION: EIcon;
        private static _KEY;
        static readonly KEY: EIcon;
        private static _KEYBOARD_O;
        static readonly KEYBOARD_O: EIcon;
        private static _LANGUAGE;
        static readonly LANGUAGE: EIcon;
        private static _LAPTOP;
        static readonly LAPTOP: EIcon;
        private static _LEAF;
        static readonly LEAF: EIcon;
        private static _LEGAL;
        static readonly LEGAL: EIcon;
        private static _LEMON_O;
        static readonly LEMON_O: EIcon;
        private static _LEVEL_DOWN;
        static readonly LEVEL_DOWN: EIcon;
        private static _LEVEL_UP;
        static readonly LEVEL_UP: EIcon;
        private static _LIFE_BOUY;
        static readonly LIFE_BOUY: EIcon;
        private static _LIFE_BUOY;
        static readonly LIFE_BUOY: EIcon;
        private static _LIFE_RING;
        static readonly LIFE_RING: EIcon;
        private static _LIFE_SAVER;
        static readonly LIFE_SAVER: EIcon;
        private static _LIGHTBULB_O;
        static readonly LIGHTBULB_O: EIcon;
        private static _LINE_CHART;
        static readonly LINE_CHART: EIcon;
        private static _LOCATION_ARROW;
        static readonly LOCATION_ARROW: EIcon;
        private static _LOCK;
        static readonly LOCK: EIcon;
        private static _MAGIC;
        static readonly MAGIC: EIcon;
        private static _MAGNET;
        static readonly MAGNET: EIcon;
        private static _MAIL_FORWARD;
        static readonly MAIL_FORWARD: EIcon;
        private static _MAIL_REPLY;
        static readonly MAIL_REPLY: EIcon;
        private static _MAIL_REPLY_ALL;
        static readonly MAIL_REPLY_ALL: EIcon;
        private static _MALE;
        static readonly MALE: EIcon;
        private static _MAP_MARKER;
        static readonly MAP_MARKER: EIcon;
        private static _MEH_O;
        static readonly MEH_O: EIcon;
        private static _MICROPHONE;
        static readonly MICROPHONE: EIcon;
        private static _MICROPHONE_SLASH;
        static readonly MICROPHONE_SLASH: EIcon;
        private static _MINUS;
        static readonly MINUS: EIcon;
        private static _MINUS_CIRCLE;
        static readonly MINUS_CIRCLE: EIcon;
        private static _MINUS_SQUARE;
        static readonly MINUS_SQUARE: EIcon;
        private static _MINUS_SQUARE_O;
        static readonly MINUS_SQUARE_O: EIcon;
        private static _MOBILE;
        static readonly MOBILE: EIcon;
        private static _MOBILE_PHONE;
        static readonly MOBILE_PHONE: EIcon;
        private static _MONEY;
        static readonly MONEY: EIcon;
        private static _MOON_O;
        static readonly MOON_O: EIcon;
        private static _MORTAR_BOARD;
        static readonly MORTAR_BOARD: EIcon;
        private static _MOTORCYCLE;
        static readonly MOTORCYCLE: EIcon;
        private static _MUSIC;
        static readonly MUSIC: EIcon;
        private static _NAVICON;
        static readonly NAVICON: EIcon;
        private static _NEWSPAPER_O;
        static readonly NEWSPAPER_O: EIcon;
        private static _PAINT_BRUSH;
        static readonly PAINT_BRUSH: EIcon;
        private static _PAPER_PLANE;
        static readonly PAPER_PLANE: EIcon;
        private static _PAPER_PLANE_O;
        static readonly PAPER_PLANE_O: EIcon;
        private static _PAW;
        static readonly PAW: EIcon;
        private static _PENCIL;
        static readonly PENCIL: EIcon;
        private static _PENCIL_SQUARE;
        static readonly PENCIL_SQUARE: EIcon;
        private static _PENCIL_SQUARE_O;
        static readonly PENCIL_SQUARE_O: EIcon;
        private static _PHONE;
        static readonly PHONE: EIcon;
        private static _PHONE_SQUARE;
        static readonly PHONE_SQUARE: EIcon;
        private static _PHOTO;
        static readonly PHOTO: EIcon;
        private static _PICTURE_O;
        static readonly PICTURE_O: EIcon;
        private static _PIE_CHART;
        static readonly PIE_CHART: EIcon;
        private static _PLANE;
        static readonly PLANE: EIcon;
        private static _PLUG;
        static readonly PLUG: EIcon;
        private static _PLUS;
        static readonly PLUS: EIcon;
        private static _PLUS_CIRCLE;
        static readonly PLUS_CIRCLE: EIcon;
        private static _PLUS_SQUARE;
        static readonly PLUS_SQUARE: EIcon;
        private static _PLUS_SQUARE_O;
        static readonly PLUS_SQUARE_O: EIcon;
        private static _POWER_OFF;
        static readonly POWER_OFF: EIcon;
        private static _PRINT;
        static readonly PRINT: EIcon;
        private static _PUZZLE_PIECE;
        static readonly PUZZLE_PIECE: EIcon;
        private static _QRCODE;
        static readonly QRCODE: EIcon;
        private static _QUESTION;
        static readonly QUESTION: EIcon;
        private static _QUESTION_CIRCLE;
        static readonly QUESTION_CIRCLE: EIcon;
        private static _QUOTE_LEFT;
        static readonly QUOTE_LEFT: EIcon;
        private static _QUOTE_RIGHT;
        static readonly QUOTE_RIGHT: EIcon;
        private static _RANDOM;
        static readonly RANDOM: EIcon;
        private static _RECYCLE;
        static readonly RECYCLE: EIcon;
        private static _REFRESH;
        static readonly REFRESH: EIcon;
        private static _REMOVE;
        static readonly REMOVE: EIcon;
        private static _REORDER;
        static readonly REORDER: EIcon;
        private static _REPLY;
        static readonly REPLY: EIcon;
        private static _REPLY_ALL;
        static readonly REPLY_ALL: EIcon;
        private static _RETWEET;
        static readonly RETWEET: EIcon;
        private static _ROAD;
        static readonly ROAD: EIcon;
        private static _ROCKET;
        static readonly ROCKET: EIcon;
        private static _RSS;
        static readonly RSS: EIcon;
        private static _RSS_SQUARE;
        static readonly RSS_SQUARE: EIcon;
        private static _SEARCH;
        static readonly SEARCH: EIcon;
        private static _SEARCH_MINUS;
        static readonly SEARCH_MINUS: EIcon;
        private static _SEARCH_PLUS;
        static readonly SEARCH_PLUS: EIcon;
        private static _SEND;
        static readonly SEND: EIcon;
        private static _SEND_O;
        static readonly SEND_O: EIcon;
        private static _SERVER;
        static readonly SERVER: EIcon;
        private static _SHARE;
        static readonly SHARE: EIcon;
        private static _SHARE_ALT;
        static readonly SHARE_ALT: EIcon;
        private static _SHARE_ALT_SQUARE;
        static readonly SHARE_ALT_SQUARE: EIcon;
        private static _SHARE_SQUARE;
        static readonly SHARE_SQUARE: EIcon;
        private static _SHARE_SQUARE_O;
        static readonly SHARE_SQUARE_O: EIcon;
        private static _SHIELD;
        static readonly SHIELD: EIcon;
        private static _SHIP;
        static readonly SHIP: EIcon;
        private static _SHOPPING_CART;
        static readonly SHOPPING_CART: EIcon;
        private static _SIGN_IN;
        static readonly SIGN_IN: EIcon;
        private static _SIGN_OUT;
        static readonly SIGN_OUT: EIcon;
        private static _SIGNAL;
        static readonly SIGNAL: EIcon;
        private static _SITEMAP;
        static readonly SITEMAP: EIcon;
        private static _SLIDERS;
        static readonly SLIDERS: EIcon;
        private static _SMILE_O;
        static readonly SMILE_O: EIcon;
        private static _SOCCER_BALL_O;
        static readonly SOCCER_BALL_O: EIcon;
        private static _SORT;
        static readonly SORT: EIcon;
        private static _SORT_ALPHA_ASC;
        static readonly SORT_ALPHA_ASC: EIcon;
        private static _SORT_ALPHA_DESC;
        static readonly SORT_ALPHA_DESC: EIcon;
        private static _SORT_AMOUNT_ASC;
        static readonly SORT_AMOUNT_ASC: EIcon;
        private static _SORT_AMOUNT_DESC;
        static readonly SORT_AMOUNT_DESC: EIcon;
        private static _SORT_ASC;
        static readonly SORT_ASC: EIcon;
        private static _SORT_DESC;
        static readonly SORT_DESC: EIcon;
        private static _SORT_DOWN;
        static readonly SORT_DOWN: EIcon;
        private static _SORT_NUMERIC_ASC;
        static readonly SORT_NUMERIC_ASC: EIcon;
        private static _SORT_NUMERIC_DESC;
        static readonly SORT_NUMERIC_DESC: EIcon;
        private static _SORT_UP;
        static readonly SORT_UP: EIcon;
        private static _SPACE_SHUTTLE;
        static readonly SPACE_SHUTTLE: EIcon;
        private static _SPINNER;
        static readonly SPINNER: EIcon;
        private static _SPOON;
        static readonly SPOON: EIcon;
        private static _SQUARE;
        static readonly SQUARE: EIcon;
        private static _SQUARE_O;
        static readonly SQUARE_O: EIcon;
        private static _STAR;
        static readonly STAR: EIcon;
        private static _STAR_HALF;
        static readonly STAR_HALF: EIcon;
        private static _STAR_HALF_EMPTY;
        static readonly STAR_HALF_EMPTY: EIcon;
        private static _STAR_HALF_FULL;
        static readonly STAR_HALF_FULL: EIcon;
        private static _STAR_HALF_O;
        static readonly STAR_HALF_O: EIcon;
        private static _STAR_O;
        static readonly STAR_O: EIcon;
        private static _STREET_VIEW;
        static readonly STREET_VIEW: EIcon;
        private static _SUITCASE;
        static readonly SUITCASE: EIcon;
        private static _SUN_O;
        static readonly SUN_O: EIcon;
        private static _SUPPORT;
        static readonly SUPPORT: EIcon;
        private static _TABLET;
        static readonly TABLET: EIcon;
        private static _TACHOMETER;
        static readonly TACHOMETER: EIcon;
        private static _TAG;
        static readonly TAG: EIcon;
        private static _TAGS;
        static readonly TAGS: EIcon;
        private static _TASKS;
        static readonly TASKS: EIcon;
        private static _TAXI;
        static readonly TAXI: EIcon;
        private static _TERMINAL;
        static readonly TERMINAL: EIcon;
        private static _THUMB_TACK;
        static readonly THUMB_TACK: EIcon;
        private static _THUMBS_DOWN;
        static readonly THUMBS_DOWN: EIcon;
        private static _THUMBS_O_DOWN;
        static readonly THUMBS_O_DOWN: EIcon;
        private static _THUMBS_O_UP;
        static readonly THUMBS_O_UP: EIcon;
        private static _THUMBS_UP;
        static readonly THUMBS_UP: EIcon;
        private static _TICKET;
        static readonly TICKET: EIcon;
        private static _TIMES;
        static readonly TIMES: EIcon;
        private static _TIMES_CIRCLE;
        static readonly TIMES_CIRCLE: EIcon;
        private static _TIMES_CIRCLE_O;
        static readonly TIMES_CIRCLE_O: EIcon;
        private static _TINT;
        static readonly TINT: EIcon;
        private static _TOGGLE_DOWN;
        static readonly TOGGLE_DOWN: EIcon;
        private static _TOGGLE_LEFT;
        static readonly TOGGLE_LEFT: EIcon;
        private static _TOGGLE_OFF;
        static readonly TOGGLE_OFF: EIcon;
        private static _TOGGLE_ON;
        static readonly TOGGLE_ON: EIcon;
        private static _TOGGLE_RIGHT;
        static readonly TOGGLE_RIGHT: EIcon;
        private static _TOGGLE_UP;
        static readonly TOGGLE_UP: EIcon;
        private static _TRASH;
        static readonly TRASH: EIcon;
        private static _TRASH_O;
        static readonly TRASH_O: EIcon;
        private static _TREE;
        static readonly TREE: EIcon;
        private static _TROPHY;
        static readonly TROPHY: EIcon;
        private static _TRUCK;
        static readonly TRUCK: EIcon;
        private static _TTY;
        static readonly TTY: EIcon;
        private static _UMBRELLA;
        static readonly UMBRELLA: EIcon;
        private static _UNIVERSITY;
        static readonly UNIVERSITY: EIcon;
        private static _UNLOCK;
        static readonly UNLOCK: EIcon;
        private static _UNLOCK_ALT;
        static readonly UNLOCK_ALT: EIcon;
        private static _UNSORTED;
        static readonly UNSORTED: EIcon;
        private static _UPLOAD;
        static readonly UPLOAD: EIcon;
        private static _USER;
        static readonly USER: EIcon;
        private static _USER_PLUS;
        static readonly USER_PLUS: EIcon;
        private static _USER_SECRET;
        static readonly USER_SECRET: EIcon;
        private static _USER_TIMES;
        static readonly USER_TIMES: EIcon;
        private static _USERS;
        static readonly USERS: EIcon;
        private static _VIDEO_CAMERA;
        static readonly VIDEO_CAMERA: EIcon;
        private static _VOLUME_DOWN;
        static readonly VOLUME_DOWN: EIcon;
        private static _VOLUME_OFF;
        static readonly VOLUME_OFF: EIcon;
        private static _VOLUME_UP;
        static readonly VOLUME_UP: EIcon;
        private static _WARNING;
        static readonly WARNING: EIcon;
        private static _WHEELCHAIR;
        static readonly WHEELCHAIR: EIcon;
        private static _WIFI;
        static readonly WIFI: EIcon;
        private static _WRENCH;
        static readonly WRENCH: EIcon;
        private static _HAND_O_DOWN;
        static readonly HAND_O_DOWN: EIcon;
        private static _HAND_O_LEFT;
        static readonly HAND_O_LEFT: EIcon;
        private static _HAND_O_RIGHT;
        static readonly HAND_O_RIGHT: EIcon;
        private static _HAND_O_UP;
        static readonly HAND_O_UP: EIcon;
        private static _AMBULANCE;
        static readonly AMBULANCE: EIcon;
        private static _SUBWAY;
        static readonly SUBWAY: EIcon;
        private static _TRAIN;
        static readonly TRAIN: EIcon;
        private static _INTERSEX;
        static readonly INTERSEX: EIcon;
        private static _MARS;
        static readonly MARS: EIcon;
        private static _MARS_DOUBLE;
        static readonly MARS_DOUBLE: EIcon;
        private static _MARS_STROKE;
        static readonly MARS_STROKE: EIcon;
        private static _MARS_STROKE_H;
        static readonly MARS_STROKE_H: EIcon;
        private static _MARS_STROKE_V;
        static readonly MARS_STROKE_V: EIcon;
        private static _MERCURY;
        static readonly MERCURY: EIcon;
        private static _NEUTER;
        static readonly NEUTER: EIcon;
        private static _TRANSGENDER;
        static readonly TRANSGENDER: EIcon;
        private static _TRANSGENDER_ALT;
        static readonly TRANSGENDER_ALT: EIcon;
        private static _VENUS;
        static readonly VENUS: EIcon;
        private static _VENUS_DOUBLE;
        static readonly VENUS_DOUBLE: EIcon;
        private static _VENUS_MARS;
        static readonly VENUS_MARS: EIcon;
        private static _FILE;
        static readonly FILE: EIcon;
        private static _FILE_O;
        static readonly FILE_O: EIcon;
        private static _FILE_TEXT;
        static readonly FILE_TEXT: EIcon;
        private static _FILE_TEXT_O;
        static readonly FILE_TEXT_O: EIcon;
        private static _CC_AMEX;
        static readonly CC_AMEX: EIcon;
        private static _CC_DISCOVER;
        static readonly CC_DISCOVER: EIcon;
        private static _CC_MASTERCARD;
        static readonly CC_MASTERCARD: EIcon;
        private static _CC_PAYPAL;
        static readonly CC_PAYPAL: EIcon;
        private static _CC_STRIPE;
        static readonly CC_STRIPE: EIcon;
        private static _CC_VISA;
        static readonly CC_VISA: EIcon;
        private static _GOOGLE_WALLET;
        static readonly GOOGLE_WALLET: EIcon;
        private static _PAYPAL;
        static readonly PAYPAL: EIcon;
        private static _BITCOIN;
        static readonly BITCOIN: EIcon;
        private static _BTC;
        static readonly BTC: EIcon;
        private static _CNY;
        static readonly CNY: EIcon;
        private static _DOLLAR;
        static readonly DOLLAR: EIcon;
        private static _EUR;
        static readonly EUR: EIcon;
        private static _EURO;
        static readonly EURO: EIcon;
        private static _GBP;
        static readonly GBP: EIcon;
        private static _ILS;
        static readonly ILS: EIcon;
        private static _INR;
        static readonly INR: EIcon;
        private static _JPY;
        static readonly JPY: EIcon;
        private static _KRW;
        static readonly KRW: EIcon;
        private static _RMB;
        static readonly RMB: EIcon;
        private static _ROUBLE;
        static readonly ROUBLE: EIcon;
        private static _RUB;
        static readonly RUB: EIcon;
        private static _RUBLE;
        static readonly RUBLE: EIcon;
        private static _RUPEE;
        static readonly RUPEE: EIcon;
        private static _SHEKEL;
        static readonly SHEKEL: EIcon;
        private static _SHEQEL;
        static readonly SHEQEL: EIcon;
        private static _TRY;
        static readonly TRY: EIcon;
        private static _TURKISH_LIRA;
        static readonly TURKISH_LIRA: EIcon;
        private static _USD;
        static readonly USD: EIcon;
        private static _WON;
        static readonly WON: EIcon;
        private static _YEN;
        static readonly YEN: EIcon;
        private static _ALIGN_CENTER;
        static readonly ALIGN_CENTER: EIcon;
        private static _ALIGN_JUSTIFY;
        static readonly ALIGN_JUSTIFY: EIcon;
        private static _ALIGN_LEFT;
        static readonly ALIGN_LEFT: EIcon;
        private static _ALIGN_RIGHT;
        static readonly ALIGN_RIGHT: EIcon;
        private static _BOLD;
        static readonly BOLD: EIcon;
        private static _CHAIN;
        static readonly CHAIN: EIcon;
        private static _CHAIN_BROKEN;
        static readonly CHAIN_BROKEN: EIcon;
        private static _CLIPBOARD;
        static readonly CLIPBOARD: EIcon;
        private static _COLUMNS;
        static readonly COLUMNS: EIcon;
        private static _COPY;
        static readonly COPY: EIcon;
        private static _CUT;
        static readonly CUT: EIcon;
        private static _DEDENT;
        static readonly DEDENT: EIcon;
        private static _FILES_O;
        static readonly FILES_O: EIcon;
        private static _FLOPPY_O;
        static readonly FLOPPY_O: EIcon;
        private static _FONT;
        static readonly FONT: EIcon;
        private static _HEADER;
        static readonly HEADER: EIcon;
        private static _INDENT;
        static readonly INDENT: EIcon;
        private static _ITALIC;
        static readonly ITALIC: EIcon;
        private static _LINK;
        static readonly LINK: EIcon;
        private static _LIST;
        static readonly LIST: EIcon;
        private static _LIST_ALT;
        static readonly LIST_ALT: EIcon;
        private static _LIST_OL;
        static readonly LIST_OL: EIcon;
        private static _LIST_UL;
        static readonly LIST_UL: EIcon;
        private static _OUTDENT;
        static readonly OUTDENT: EIcon;
        private static _PAPERCLIP;
        static readonly PAPERCLIP: EIcon;
        private static _PARAGRAPH;
        static readonly PARAGRAPH: EIcon;
        private static _PASTE;
        static readonly PASTE: EIcon;
        private static _REPEAT;
        static readonly REPEAT: EIcon;
        private static _ROTATE_LEFT;
        static readonly ROTATE_LEFT: EIcon;
        private static _ROTATE_RIGHT;
        static readonly ROTATE_RIGHT: EIcon;
        private static _SAVE;
        static readonly SAVE: EIcon;
        private static _SCISSORS;
        static readonly SCISSORS: EIcon;
        private static _STRIKETHROUGH;
        static readonly STRIKETHROUGH: EIcon;
        private static _SUBSCRIPT;
        static readonly SUBSCRIPT: EIcon;
        private static _SUPERSCRIPT;
        static readonly SUPERSCRIPT: EIcon;
        private static _TABLE;
        static readonly TABLE: EIcon;
        private static _TEXT_HEIGHT;
        static readonly TEXT_HEIGHT: EIcon;
        private static _TEXT_WIDTH;
        static readonly TEXT_WIDTH: EIcon;
        private static _TH;
        static readonly TH: EIcon;
        private static _TH_LARGE;
        static readonly TH_LARGE: EIcon;
        private static _TH_LIST;
        static readonly TH_LIST: EIcon;
        private static _UNDERLINE;
        static readonly UNDERLINE: EIcon;
        private static _UNDO;
        static readonly UNDO: EIcon;
        private static _UNLINK;
        static readonly UNLINK: EIcon;
        private static _ANGLE_DOUBLE_DOWN;
        static readonly ANGLE_DOUBLE_DOWN: EIcon;
        private static _ANGLE_DOUBLE_LEFT;
        static readonly ANGLE_DOUBLE_LEFT: EIcon;
        private static _ANGLE_DOUBLE_RIGHT;
        static readonly ANGLE_DOUBLE_RIGHT: EIcon;
        private static _ANGLE_DOUBLE_UP;
        static readonly ANGLE_DOUBLE_UP: EIcon;
        private static _ANGLE_DOWN;
        static readonly ANGLE_DOWN: EIcon;
        private static _ANGLE_LEFT;
        static readonly ANGLE_LEFT: EIcon;
        private static _ANGLE_RIGHT;
        static readonly ANGLE_RIGHT: EIcon;
        private static _ANGLE_UP;
        static readonly ANGLE_UP: EIcon;
        private static _ARROW_CIRCLE_DOWN;
        static readonly ARROW_CIRCLE_DOWN: EIcon;
        private static _ARROW_CIRCLE_LEFT;
        static readonly ARROW_CIRCLE_LEFT: EIcon;
        private static _ARROW_CIRCLE_O_DOWN;
        static readonly ARROW_CIRCLE_O_DOWN: EIcon;
        private static _ARROW_CIRCLE_O_LEFT;
        static readonly ARROW_CIRCLE_O_LEFT: EIcon;
        private static _ARROW_CIRCLE_O_RIGHT;
        static readonly ARROW_CIRCLE_O_RIGHT: EIcon;
        private static _ARROW_CIRCLE_O_UP;
        static readonly ARROW_CIRCLE_O_UP: EIcon;
        private static _ARROW_CIRCLE_RIGHT;
        static readonly ARROW_CIRCLE_RIGHT: EIcon;
        private static _ARROW_CIRCLE_UP;
        static readonly ARROW_CIRCLE_UP: EIcon;
        private static _ARROW_DOWN;
        static readonly ARROW_DOWN: EIcon;
        private static _ARROW_LEFT;
        static readonly ARROW_LEFT: EIcon;
        private static _ARROW_RIGHT;
        static readonly ARROW_RIGHT: EIcon;
        private static _ARROW_UP;
        static readonly ARROW_UP: EIcon;
        private static _ARROWS_ALT;
        static readonly ARROWS_ALT: EIcon;
        private static _CARET_DOWN;
        static readonly CARET_DOWN: EIcon;
        private static _CARET_LEFT;
        static readonly CARET_LEFT: EIcon;
        private static _CARET_RIGHT;
        static readonly CARET_RIGHT: EIcon;
        private static _CARET_UP;
        static readonly CARET_UP: EIcon;
        private static _CHEVRON_CIRCLE_DOWN;
        static readonly CHEVRON_CIRCLE_DOWN: EIcon;
        private static _CHEVRON_CIRCLE_LEFT;
        static readonly CHEVRON_CIRCLE_LEFT: EIcon;
        private static _CHEVRON_CIRCLE_RIGHT;
        static readonly CHEVRON_CIRCLE_RIGHT: EIcon;
        private static _CHEVRON_CIRCLE_UP;
        static readonly CHEVRON_CIRCLE_UP: EIcon;
        private static _CHEVRON_DOWN;
        static readonly CHEVRON_DOWN: EIcon;
        private static _CHEVRON_LEFT;
        static readonly CHEVRON_LEFT: EIcon;
        private static _CHEVRON_RIGHT;
        static readonly CHEVRON_RIGHT: EIcon;
        private static _CHEVRON_UP;
        static readonly CHEVRON_UP: EIcon;
        private static _LONG_ARROW_DOWN;
        static readonly LONG_ARROW_DOWN: EIcon;
        private static _LONG_ARROW_LEFT;
        static readonly LONG_ARROW_LEFT: EIcon;
        private static _LONG_ARROW_RIGHT;
        static readonly LONG_ARROW_RIGHT: EIcon;
        private static _LONG_ARROW_UP;
        static readonly LONG_ARROW_UP: EIcon;
        private static _BACKWARD;
        static readonly BACKWARD: EIcon;
        private static _COMPRESS;
        static readonly COMPRESS: EIcon;
        private static _EJECT;
        static readonly EJECT: EIcon;
        private static _EXPAND;
        static readonly EXPAND: EIcon;
        private static _FAST_BACKWARD;
        static readonly FAST_BACKWARD: EIcon;
        private static _FAST_FORWARD;
        static readonly FAST_FORWARD: EIcon;
        private static _FORWARD;
        static readonly FORWARD: EIcon;
        private static _PAUSE;
        static readonly PAUSE: EIcon;
        private static _PLAY;
        static readonly PLAY: EIcon;
        private static _PLAY_CIRCLE;
        static readonly PLAY_CIRCLE: EIcon;
        private static _PLAY_CIRCLE_O;
        static readonly PLAY_CIRCLE_O: EIcon;
        private static _STEP_BACKWARD;
        static readonly STEP_BACKWARD: EIcon;
        private static _STEP_FORWARD;
        static readonly STEP_FORWARD: EIcon;
        private static _STOP;
        static readonly STOP: EIcon;
        private static _YOUTUBE_PLAY;
        static readonly YOUTUBE_PLAY: EIcon;
        private static _ADN;
        static readonly ADN: EIcon;
        private static _ANDROID;
        static readonly ANDROID: EIcon;
        private static _ANGELLIST;
        static readonly ANGELLIST: EIcon;
        private static _APPLE;
        static readonly APPLE: EIcon;
        private static _BEHANCE;
        static readonly BEHANCE: EIcon;
        private static _BEHANCE_SQUARE;
        static readonly BEHANCE_SQUARE: EIcon;
        private static _BITBUCKET;
        static readonly BITBUCKET: EIcon;
        private static _BITBUCKET_SQUARE;
        static readonly BITBUCKET_SQUARE: EIcon;
        private static _BUYSELLADS;
        static readonly BUYSELLADS: EIcon;
        private static _CODEPEN;
        static readonly CODEPEN: EIcon;
        private static _CONNECTDEVELOP;
        static readonly CONNECTDEVELOP: EIcon;
        private static _CSS3;
        static readonly CSS3: EIcon;
        private static _DASHCUBE;
        static readonly DASHCUBE: EIcon;
        private static _DELICIOUS;
        static readonly DELICIOUS: EIcon;
        private static _DEVIANTART;
        static readonly DEVIANTART: EIcon;
        private static _DIGG;
        static readonly DIGG: EIcon;
        private static _DRIBBBLE;
        static readonly DRIBBBLE: EIcon;
        private static _DROPBOX;
        static readonly DROPBOX: EIcon;
        private static _DRUPAL;
        static readonly DRUPAL: EIcon;
        private static _EMPIRE;
        static readonly EMPIRE: EIcon;
        private static _FACEBOOK;
        static readonly FACEBOOK: EIcon;
        private static _FACEBOOK_F;
        static readonly FACEBOOK_F: EIcon;
        private static _FACEBOOK_OFFICIAL;
        static readonly FACEBOOK_OFFICIAL: EIcon;
        private static _FACEBOOK_SQUARE;
        static readonly FACEBOOK_SQUARE: EIcon;
        private static _FLICKR;
        static readonly FLICKR: EIcon;
        private static _FORUMBEE;
        static readonly FORUMBEE: EIcon;
        private static _FOURSQUARE;
        static readonly FOURSQUARE: EIcon;
        private static _GE;
        static readonly GE: EIcon;
        private static _GIT;
        static readonly GIT: EIcon;
        private static _GIT_SQUARE;
        static readonly GIT_SQUARE: EIcon;
        private static _GITHUB;
        static readonly GITHUB: EIcon;
        private static _GITHUB_ALT;
        static readonly GITHUB_ALT: EIcon;
        private static _GITHUB_SQUARE;
        static readonly GITHUB_SQUARE: EIcon;
        private static _GITTIP;
        static readonly GITTIP: EIcon;
        private static _GOOGLE;
        static readonly GOOGLE: EIcon;
        private static _GOOGLE_PLUS;
        static readonly GOOGLE_PLUS: EIcon;
        private static _GOOGLE_PLUS_SQUARE;
        static readonly GOOGLE_PLUS_SQUARE: EIcon;
        private static _GRATIPAY;
        static readonly GRATIPAY: EIcon;
        private static _HACKER_NEWS;
        static readonly HACKER_NEWS: EIcon;
        private static _HTML5;
        static readonly HTML5: EIcon;
        private static _INSTAGRAM;
        static readonly INSTAGRAM: EIcon;
        private static _IOXHOST;
        static readonly IOXHOST: EIcon;
        private static _JOOMLA;
        static readonly JOOMLA: EIcon;
        private static _JSFIDDLE;
        static readonly JSFIDDLE: EIcon;
        private static _LASTFM;
        static readonly LASTFM: EIcon;
        private static _LASTFM_SQUARE;
        static readonly LASTFM_SQUARE: EIcon;
        private static _LEANPUB;
        static readonly LEANPUB: EIcon;
        private static _LINKEDIN;
        static readonly LINKEDIN: EIcon;
        private static _LINKEDIN_SQUARE;
        static readonly LINKEDIN_SQUARE: EIcon;
        private static _LINUX;
        static readonly LINUX: EIcon;
        private static _MAXCDN;
        static readonly MAXCDN: EIcon;
        private static _MEANPATH;
        static readonly MEANPATH: EIcon;
        private static _MEDIUM;
        static readonly MEDIUM: EIcon;
        private static _OPENID;
        static readonly OPENID: EIcon;
        private static _PAGELINES;
        static readonly PAGELINES: EIcon;
        private static _PIED_PIPER;
        static readonly PIED_PIPER: EIcon;
        private static _PIED_PIPER_ALT;
        static readonly PIED_PIPER_ALT: EIcon;
        private static _PINTEREST;
        static readonly PINTEREST: EIcon;
        private static _PINTEREST_P;
        static readonly PINTEREST_P: EIcon;
        private static _PINTEREST_SQUARE;
        static readonly PINTEREST_SQUARE: EIcon;
        private static _QQ;
        static readonly QQ: EIcon;
        private static _RA;
        static readonly RA: EIcon;
        private static _REBEL;
        static readonly REBEL: EIcon;
        private static _REDDIT;
        static readonly REDDIT: EIcon;
        private static _REDDIT_SQUARE;
        static readonly REDDIT_SQUARE: EIcon;
        private static _RENREN;
        static readonly RENREN: EIcon;
        private static _SELLSY;
        static readonly SELLSY: EIcon;
        private static _SHIRTSINBULK;
        static readonly SHIRTSINBULK: EIcon;
        private static _SIMPLYBUILT;
        static readonly SIMPLYBUILT: EIcon;
        private static _SKYATLAS;
        static readonly SKYATLAS: EIcon;
        private static _SKYPE;
        static readonly SKYPE: EIcon;
        private static _SLACK;
        static readonly SLACK: EIcon;
        private static _SLIDESHARE;
        static readonly SLIDESHARE: EIcon;
        private static _SOUNDCLOUD;
        static readonly SOUNDCLOUD: EIcon;
        private static _SPOTIFY;
        static readonly SPOTIFY: EIcon;
        private static _STACK_EXCHANGE;
        static readonly STACK_EXCHANGE: EIcon;
        private static _STACK_OVERFLOW;
        static readonly STACK_OVERFLOW: EIcon;
        private static _STEAM;
        static readonly STEAM: EIcon;
        private static _STEAM_SQUARE;
        static readonly STEAM_SQUARE: EIcon;
        private static _STUMBLEUPON;
        static readonly STUMBLEUPON: EIcon;
        private static _STUMBLEUPON_CIRCLE;
        static readonly STUMBLEUPON_CIRCLE: EIcon;
        private static _TENCENT_WEIBO;
        static readonly TENCENT_WEIBO: EIcon;
        private static _TRELLO;
        static readonly TRELLO: EIcon;
        private static _TUMBLR;
        static readonly TUMBLR: EIcon;
        private static _TUMBLR_SQUARE;
        static readonly TUMBLR_SQUARE: EIcon;
        private static _TWITCH;
        static readonly TWITCH: EIcon;
        private static _TWITTER;
        static readonly TWITTER: EIcon;
        private static _TWITTER_SQUARE;
        static readonly TWITTER_SQUARE: EIcon;
        private static _VIACOIN;
        static readonly VIACOIN: EIcon;
        private static _VIMEO_SQUARE;
        static readonly VIMEO_SQUARE: EIcon;
        private static _VINE;
        static readonly VINE: EIcon;
        private static _VK;
        static readonly VK: EIcon;
        private static _WECHAT;
        static readonly WECHAT: EIcon;
        private static _WEIBO;
        static readonly WEIBO: EIcon;
        private static _WEIXIN;
        static readonly WEIXIN: EIcon;
        private static _WHATSAPP;
        static readonly WHATSAPP: EIcon;
        private static _WINDOWS;
        static readonly WINDOWS: EIcon;
        private static _WORDPRESS;
        static readonly WORDPRESS: EIcon;
        private static _XING;
        static readonly XING: EIcon;
        private static _XING_SQUARE;
        static readonly XING_SQUARE: EIcon;
        private static _Y_COMBINATOR_SQUARE;
        static readonly Y_COMBINATOR_SQUARE: EIcon;
        private static _YAHOO;
        static readonly YAHOO: EIcon;
        private static _YC_SQUARE;
        static readonly YC_SQUARE: EIcon;
        private static _YELP;
        static readonly YELP: EIcon;
        private static _YOUTUBE;
        static readonly YOUTUBE: EIcon;
        private static _YOUTUBE_SQUARE;
        static readonly YOUTUBE_SQUARE: EIcon;
        constructor(_value: string);
        readonly className: string;
    }
}
declare namespace cubee {
    class APopup {
        private _modal;
        private _autoClose;
        private _glassColor;
        private _translateX;
        private _translateY;
        private _center;
        private _popupRoot;
        private _rootComponentContainer;
        private _rootComponent;
        private _visible;
        constructor(modal?: boolean, autoClose?: boolean, glassColor?: Color);
        readonly __popupRoot: Panel;
        protected rootComponent: AComponent;
        protected show(): void;
        protected close(): boolean;
        protected isCloseAllowed(): boolean;
        protected onClosed(): void;
        readonly modal: boolean;
        readonly autoClose: boolean;
        readonly glassColor: Color;
        readonly TranslateX: NumberProperty;
        translateX: number;
        readonly TranslateY: NumberProperty;
        translateY: number;
        readonly Center: BooleanProperty;
        center: boolean;
        _layout(): void;
    }
    class Popups {
        private static _popups;
        private static _layoutRunOnce;
        static _addPopup(popup: APopup): void;
        static _removePopup(popup: APopup): void;
        static _requestLayout(): void;
        private static layout();
        constructor();
    }
}
declare namespace cubee {
    class CubeePanel {
        private _layoutRunOnce;
        private _contentPanel;
        private _rootComponent;
        private _element;
        private _left;
        private _top;
        private _clientWidth;
        private _clientHeight;
        private _offsetWidth;
        private _offsetHeight;
        constructor(element: HTMLDivElement);
        private checkBounds();
        requestLayout(): void;
        layout(): void;
        rootComponent: AComponent;
        readonly ClientWidth: NumberProperty;
        clientWidth: number;
        readonly ClientHeight: NumberProperty;
        clientHeight: number;
        readonly BoundsWidth: NumberProperty;
        boundsWidth: number;
        readonly BoundsHeight: NumberProperty;
        boundsHeight: number;
        readonly BoundsLeft: NumberProperty;
        boundsLeft: number;
        readonly BoundsTop: NumberProperty;
        boundsTop: number;
    }
}
