declare namespace cubee {
    class EventArgs {
        sender: Object;
        constructor(sender: Object);
    }
    interface IListenerCallback<T> {
        onAdded(listener: IEventListener<T>): void;
        onRemoved(listener: IEventListener<T>): void;
    }
    class HtmlEventListenerCallback<T> implements IListenerCallback<T> {
        private _element;
        private _eventType;
        constructor(_element: HTMLElement, _eventType: string);
        onAdded(listener: IEventListener<T>): void;
        onRemoved(listener: IEventListener<T>): void;
    }
    class Event<T> {
        private _listenerCallback;
        private _listeners;
        constructor(_listenerCallback?: IListenerCallback<T>);
        addListener(listener: IEventListener<T>): void;
        removeListener(listener: IEventListener<T>): void;
        hasListener(listener: IEventListener<T>): boolean;
        fireEvent(args: T): void;
        listenerCallback: IListenerCallback<T>;
    }
    class Timer {
        private func;
        private token;
        private repeat;
        private action;
        constructor(func: {
            (): void;
        });
        start(delay: number, repeat: boolean): void;
        stop(): void;
        Started: boolean;
    }
    interface IEventListener<T> {
        (args: T): void;
    }
    class EventQueue {
        private static instance;
        static Instance: EventQueue;
        private queue;
        private timer;
        constructor();
        invokeLater(task: {
            (): void;
        }): void;
        invokePrior(task: {
            (): void;
        }): void;
    }
    class RunOnce {
        private func;
        private scheduled;
        constructor(func: IRunnable);
        run(): void;
    }
    class ParentChangedEventArgs extends EventArgs {
        newParent: ALayout;
        sender: Object;
        constructor(newParent: ALayout, sender: Object);
    }
}
declare namespace cubee {
    interface IChangeListener {
        (sender?: Object): void;
    }
    interface IObservable {
        addChangeListener(listener: IChangeListener): void;
        removeChangeListener(listener: IChangeListener): void;
        hasChangeListener(listener: IChangeListener): void;
    }
    interface IBindable<T> {
        bind(source: T): void;
        unbind(): void;
        isBound(): boolean;
    }
    interface IAnimateable<T> {
        animate(pos: number, startValue: T, endValue: T): T;
    }
    interface IProperty<T> extends IObservable {
        getObjectValue(): Object;
        invalidate(): void;
    }
    interface IValidator<T> {
        validate(value: T): T;
    }
    class Property<T> implements IProperty<T>, IAnimateable<T>, IBindable<IProperty<T>> {
        private _value;
        private _nullable;
        private _readonly;
        private _validator;
        private static _nextId;
        private _changeListeners;
        private _valid;
        private _bindingSource;
        private _readonlyBind;
        private _bidirectionalBindProperty;
        private _bidirectionalChangeListenerThis;
        private _bidirectionalChangeListenerOther;
        private _id;
        private bindListener;
        constructor(_value?: T, _nullable?: boolean, _readonly?: boolean, _validator?: IValidator<T>);
        id: string;
        valid: boolean;
        value: T;
        nullable: boolean;
        readonly: boolean;
        initReadonlyBind(readonlyBind: IProperty<T>): void;
        private get();
        private set(newValue);
        invalidate(): void;
        invalidateIfNeeded(): void;
        fireChangeListeners(): void;
        getObjectValue(): Object;
        addChangeListener(listener: IChangeListener): void;
        removeChangeListener(listener: IChangeListener): void;
        hasChangeListener(listener: IChangeListener): boolean;
        animate(pos: number, startValue: T, endValue: T): T;
        bind(source: IProperty<T>): void;
        bidirectionalBind(other: Property<T>): void;
        unbind(): void;
        unbindTargets(): void;
        isBound(): boolean;
        isBidirectionalBound(): boolean;
        createPropertyLine(keyFrames: KeyFrame<T>[]): PropertyLine<T>;
        destroy(): void;
    }
    class Expression<T> implements IProperty<T>, IObservable {
        private _notifyListenersOnce;
        private _bindingSources;
        private _bindingListener;
        private _changeListeners;
        private _func;
        private _valid;
        private _value;
        constructor(func: {
            (): T;
        }, ...activators: IProperty<any>[]);
        value: T;
        addChangeListener(listener: IChangeListener): void;
        removeChangeListener(listener: IChangeListener): void;
        hasChangeListener(listener: IChangeListener): boolean;
        getObjectValue(): T;
        bind(...properties: IProperty<any>[]): void;
        unbindAll(): void;
        unbind(property: IProperty<any>): void;
        invalidate(): void;
        invalidateIfNeeded(): void;
        private fireChangeListeners();
    }
    class KeyFrame<T> {
        private _time;
        private _property;
        private _endValue;
        private _keyframeReachedListener;
        private _interpolator;
        constructor(_time: number, _property: Property<T>, _endValue: T, _keyframeReachedListener?: {
            (): void;
        }, _interpolator?: IInterpolator);
        time: number;
        property: Property<T>;
        endValue: T;
        interpolator: IInterpolator;
        keyFrameReachedListener: () => void;
    }
    class PropertyLine<T> {
        private _keyFrames;
        private _property;
        private _startTime;
        private _lastRunTime;
        private _previousFrame;
        constructor(_keyFrames: KeyFrame<T>[]);
        startTime: number;
        animate(): boolean;
    }
    interface IInterpolator {
        (value: number): number;
    }
    class Interpolators {
        static Linear: IInterpolator;
    }
    abstract class AAnimator {
        private static animators;
        private static ANIMATOR_TASK;
        private started;
        static animate(): void;
        start(): void;
        stop(): void;
        Started: boolean;
        Stopped: boolean;
        protected abstract onAnimate(): void;
    }
    class Timeline extends AAnimator {
        private keyFrames;
        private propertyLines;
        private repeatCount;
        private finishedEvent;
        constructor(keyFrames: KeyFrame<any>[]);
        createPropertyLines(): void;
        start(repeatCount?: number): void;
        stop(): void;
        onAnimate(): void;
        onFinishedEvent(): Event<TimelineFinishedEventArgs>;
    }
    class TimelineFinishedEventArgs {
        private stopped;
        constructor(stopped?: boolean);
        Stopped: boolean;
    }
    class NumberProperty extends Property<number> {
        animate(pos: number, startValue: number, endValue: number): number;
    }
    class StringProperty extends Property<string> {
    }
    class PaddingProperty extends Property<Padding> {
    }
    class BorderProperty extends Property<Border> {
    }
    class BackgroundProperty extends Property<ABackground> {
    }
    class BooleanProperty extends Property<boolean> {
    }
    class ColorProperty extends Property<Color> {
    }
}
declare namespace cubee {
    interface IStyle {
        apply(element: HTMLElement): void;
    }
    abstract class ABackground implements IStyle {
        abstract apply(element: HTMLElement): void;
    }
    class Color {
        private static _TRANSPARENT;
        static TRANSPARENT: Color;
        private static _WHITE;
        static WHITE: Color;
        private static _BLACK;
        static BLACK: Color;
        private static _LIGHT_GRAY;
        static LIGHT_GRAY: Color;
        static getArgbColor(argb: number): Color;
        static getArgbColorByComponents(alpha: number, red: number, green: number, blue: number): Color;
        static getRgbColor(rgb: number): Color;
        static getRgbColorByComponents(red: number, green: number, blue: number): Color;
        private static fixComponent(component);
        static fadeColors(startColor: Color, endColor: Color, fadePosition: number): Color;
        private static mixComponent(startValue, endValue, pos);
        private _argb;
        constructor(argb: number);
        argb: number;
        alpha: number;
        red: number;
        green: number;
        blue: number;
        fade(fadeColor: Color, fadePosition: number): Color;
        toCSS(): string;
    }
    class ColorBackground extends ABackground {
        private _color;
        private _cache;
        constructor(color: Color);
        color: Color;
        apply(element: HTMLElement): void;
    }
    class Padding implements IStyle {
        private _left;
        private _top;
        private _right;
        private _bottom;
        static create(padding: number): Padding;
        constructor(_left: number, _top: number, _right: number, _bottom: number);
        left: number;
        top: number;
        right: number;
        bottom: number;
        apply(element: HTMLElement): void;
    }
    class Border implements IStyle {
        private _leftWidth;
        private _topWidth;
        private _rightWidth;
        private _bottomWidth;
        private _leftColor;
        private _topColor;
        private _rightColor;
        private _bottomColor;
        private _topLeftRadius;
        private _topRightRadius;
        private _bottomLeftRadius;
        private _bottomRightRadius;
        static create(width: number, color: Color, radius: number): Border;
        constructor(_leftWidth: number, _topWidth: number, _rightWidth: number, _bottomWidth: number, _leftColor: Color, _topColor: Color, _rightColor: Color, _bottomColor: Color, _topLeftRadius: number, _topRightRadius: number, _bottomLeftRadius: number, _bottomRightRadius: number);
        leftWidth: number;
        topWidth: number;
        rightWidth: number;
        bottomWidth: number;
        leftColor: Color;
        topColor: Color;
        rightColor: Color;
        bottomColor: Color;
        topLeftRadius: number;
        topRightRadius: number;
        bottomLeftRadius: number;
        bottomRightRadius: number;
        apply(element: HTMLElement): void;
    }
    class BoxShadow implements IStyle {
        private _hPos;
        private _vPos;
        private _blur;
        private _spread;
        private _color;
        private _inner;
        constructor(_hPos: number, _vPos: number, _blur: number, _spread: number, _color: Color, _inner: boolean);
        hPos: number;
        vPos: number;
        blur: number;
        spread: number;
        color: Color;
        inner: boolean;
        apply(element: HTMLElement): void;
    }
    class ETextOverflow implements IStyle {
        private _css;
        private static _CLIP;
        private static _ELLIPSIS;
        static CLIP: ETextOverflow;
        static ELLIPSIS: ETextOverflow;
        constructor(_css: string);
        CSS: string;
        apply(element: HTMLElement): void;
    }
    class ETextAlign implements IStyle {
        private _css;
        private static _LEFT;
        private static _CENTER;
        private static _RIGHT;
        private static _JUSTIFY;
        static LEFT: ETextAlign;
        static CENTER: ETextAlign;
        static RIGHT: ETextAlign;
        static JUSTIFY: ETextAlign;
        constructor(_css: string);
        CSS: string;
        apply(element: HTMLElement): void;
    }
    class EHAlign {
        private _css;
        private static _LEFT;
        private static _CENTER;
        private static _RIGHT;
        static LEFT: EHAlign;
        static CENTER: EHAlign;
        static RIGHT: EHAlign;
        constructor(_css: string);
        CSS: string;
    }
    class EVAlign {
        private _css;
        private static _TOP;
        private static _MIDDLE;
        private static _BOTTOM;
        static TOP: EVAlign;
        static MIDDLE: EVAlign;
        static BOTTOM: EVAlign;
        constructor(_css: string);
        CSS: string;
    }
    class FontFamily implements IStyle {
        private _css;
        private static _arial;
        static Arial: FontFamily;
        private static initialized;
        private static initFontContainerStyle();
        static registerFont(name: string, src: string, extra: string): void;
        constructor(_css: string);
        CSS: string;
        apply(element: HTMLElement): void;
    }
    class ECursor {
        private _css;
        private static auto;
        static AUTO: ECursor;
        constructor(_css: string);
        css: string;
    }
    enum EScrollBarPolicy {
        VISIBLE = 0,
        AUTO = 1,
        HIDDEN = 2,
    }
    enum EPictureSizeMode {
        NORMAL = 0,
        CENTER = 1,
        STRETCH = 2,
        FILL = 3,
        ZOOM = 4,
        FIT_WIDTH = 5,
        FIT_HEIGHT = 6,
    }
    class Image implements IStyle {
        private _url;
        private _onLoad;
        private _width;
        private _height;
        private _loaded;
        constructor(_url: string);
        url: string;
        onLoad: Event<EventArgs>;
        width: number;
        height: number;
        loaded: boolean;
        apply(element: HTMLElement): void;
    }
}
declare namespace cubee {
    interface IRunnable {
        (): void;
    }
    class Point2D {
        private _x;
        private _y;
        constructor(_x: number, _y: number);
        x: number;
        y: number;
    }
}
declare namespace cubee {
    class LayoutChildren {
        private parent;
        private children;
        constructor(parent: ALayout);
        add(component: AComponent): void;
        insert(index: number, component: AComponent): void;
        removeComponent(component: AComponent): void;
        removeIndex(index: number): void;
        clear(): void;
        get(index: number): AComponent;
        indexOf(component: AComponent): number;
        size(): number;
    }
}
declare namespace cubee {
    class MouseEventTypes {
        static MOUSE_DOWN: number;
        static MOUSE_MOVE: number;
        static MOUSE_UP: number;
        static MOUSE_ENTER: number;
        static MOUSE_LEAVE: number;
        static MOUSE_WHEEL: number;
        constructor();
    }
    abstract class AComponent {
        private _translateX;
        private _translateY;
        private _rotate;
        private _scaleX;
        private _scaleY;
        private _transformCenterX;
        private _transformCenterY;
        private _padding;
        private _border;
        private _measuredWidth;
        private _measuredHeight;
        private _clientWidth;
        private _clientHeight;
        private _boundsWidth;
        private _boundsHeight;
        private _boundsLeft;
        private _boundsTop;
        private _measuredWidthSetter;
        private _measuredHeightSetter;
        private _clientWidthSetter;
        private _clientHeightSetter;
        private _boundsWidthSetter;
        private _boundsHeightSetter;
        private _boundsLeftSetter;
        private _boundsTopSetter;
        private _cursor;
        private _pointerTransparent;
        private _handlePointer;
        private _visible;
        private _enabled;
        private _alpha;
        private _selectable;
        private _minWidth;
        private _minHeight;
        private _maxWidth;
        private _maxHeight;
        private _hovered;
        private _hoveredSetter;
        private _pressed;
        private _pressedSetter;
        private _onClick;
        private _onMouseDown;
        private _onMouseDrag;
        private _onMouseMove;
        private _onMouseUp;
        private _onMouseEnter;
        private _onMouseLeave;
        private _onMouseWheel;
        private _onKeyDown;
        private _onKeyPress;
        private _onKeyUp;
        private _onParentChanged;
        private _onContextMenu;
        private _left;
        private _top;
        private _element;
        private _parent;
        _needsLayout: boolean;
        private _cubeePanel;
        private _transformChangedListener;
        private _postConstructRunOnce;
        constructor(rootElement: HTMLElement);
        private getClassName();
        private invokePostConstruct();
        protected postConstruct(): void;
        setCubeePanel(cubeePanel: CubeePanel): void;
        getCubeePanel(): CubeePanel;
        private updateTransform();
        requestLayout(): void;
        measure(): void;
        private onMeasure();
        scalePoint(centerX: number, centerY: number, pointX: number, pointY: number, scaleX: number, scaleY: number): Point2D;
        private rotatePoint(cx, cy, x, y, angle);
        element: HTMLElement;
        parent: ALayout;
        _setParent(parent: ALayout): void;
        layout(): void;
        needsLayout: boolean;
        TranslateX: NumberProperty;
        translateX: number;
        TranslateY: NumberProperty;
        translateY: number;
        protected paddingProperty(): PaddingProperty;
        protected Padding: PaddingProperty;
        protected padding: Padding;
        protected borderProperty(): BorderProperty;
        protected Border: BorderProperty;
        protected border: Border;
        MeasuredWidth: NumberProperty;
        measuredWidth: number;
        MeasuredHeight: NumberProperty;
        measuredHeight: number;
        ClientWidth: NumberProperty;
        clientWidth: number;
        ClientHeight: NumberProperty;
        clientHeight: number;
        BoundsWidth: NumberProperty;
        boundsWidth: number;
        BoundsHeight: NumberProperty;
        boundsHeight: number;
        BoundsLeft: NumberProperty;
        boundsLeft: number;
        BoundsTop: NumberProperty;
        boundsTop: number;
        protected minWidthProperty(): NumberProperty;
        protected MinWidth: NumberProperty;
        protected minWidth: number;
        protected minHeightProperty(): NumberProperty;
        protected MinHeight: NumberProperty;
        protected minHeight: number;
        protected maxWidthProperty(): NumberProperty;
        protected MaxWidth: NumberProperty;
        protected maxWidth: number;
        protected maxHeightProperty(): NumberProperty;
        protected MaxHeight: NumberProperty;
        protected maxHeight: number;
        protected setPosition(left: number, top: number): void;
        _setLeft(left: number): void;
        _setTop(top: number): void;
        protected setSize(width: number, height: number): void;
        Cursor: Property<ECursor>;
        cursor: ECursor;
        PointerTransparent: Property<boolean>;
        pointerTransparent: boolean;
        Visible: Property<boolean>;
        visible: boolean;
        onClick: Event<MouseEvent>;
        onContextMenu: Event<Object>;
        onMouseDown: Event<MouseEvent>;
        onMouseMove: Event<MouseEvent>;
        onMouseUp: Event<MouseEvent>;
        onMouseEnter: Event<MouseEvent>;
        onMouseLeave: Event<MouseEvent>;
        onMouseWheel: Event<MouseEvent>;
        onKeyDown: Event<KeyboardEvent>;
        onKeyPress: Event<KeyboardEvent>;
        onKeyUp: Event<KeyboardEvent>;
        onParentChanged: Event<ParentChangedEventArgs>;
        Alpha: NumberProperty;
        alpha: number;
        HandlePointer: Property<boolean>;
        handlePointer: boolean;
        Enabled: Property<boolean>;
        enabled: boolean;
        Selectable: Property<boolean>;
        selectable: boolean;
        left: number;
        top: number;
        Rotate: NumberProperty;
        rotate: number;
        ScaleX: NumberProperty;
        scaleX: number;
        ScaleY: NumberProperty;
        scaleY: number;
        TransformCenterX: NumberProperty;
        transformCenterX: number;
        TransformCenterY: NumberProperty;
        transformCenterY: number;
        Hovered: Property<boolean>;
        hovered: boolean;
        Pressed: Property<boolean>;
        pressed: boolean;
    }
}
declare namespace cubee {
    abstract class ALayout extends AComponent {
        private _children;
        constructor(element: HTMLElement);
        protected children_inner: LayoutChildren;
        abstract _onChildAdded(child: AComponent): void;
        abstract _onChildRemoved(child: AComponent, index: number): void;
        abstract _onChildrenCleared(): void;
        layout(): void;
        protected abstract onLayout(): void;
        getComponentsAtPosition(x: number, y: number): AComponent[];
        private getComponentsAtPosition_impl(root, x, y, result);
        protected setChildLeft(child: AComponent, left: number): void;
        protected setChildTop(child: AComponent, top: number): void;
    }
}
declare namespace cubee {
    abstract class AUserControl extends ALayout {
        private _width;
        private _height;
        private _background;
        private _shadow;
        private _draggable;
        constructor();
        protected widthProperty(): NumberProperty;
        protected Width: NumberProperty;
        protected width: number;
        protected heightProperty(): NumberProperty;
        protected Height: NumberProperty;
        protected height: number;
        protected backgroundProperty(): BackgroundProperty;
        protected Background: BackgroundProperty;
        protected background: ABackground;
        protected shadowProperty(): Property<BoxShadow>;
        protected Shadow: Property<BoxShadow>;
        protected shadow: BoxShadow;
        Draggable: BooleanProperty;
        draggable: boolean;
        _onChildAdded(child: AComponent): void;
        _onChildRemoved(child: AComponent, index: number): void;
        _onChildrenCleared(): void;
        protected onLayout(): void;
    }
}
declare namespace cubee {
    class AView<T> extends AUserControl {
        private _model;
        constructor(_model: T);
        model: T;
    }
}
declare namespace cubee {
    class Panel extends AUserControl {
        protected widthProperty(): NumberProperty;
        Width: NumberProperty;
        width: number;
        protected heightProperty(): NumberProperty;
        Height: NumberProperty;
        height: number;
        protected backgroundProperty(): BackgroundProperty;
        Background: BackgroundProperty;
        background: ABackground;
        protected shadowProperty(): Property<BoxShadow>;
        Shadow: Property<BoxShadow>;
        shadow: BoxShadow;
        children: LayoutChildren;
    }
}
declare namespace cubee {
    class HBox extends ALayout {
        private _height;
        private _cellWidths;
        private _hAligns;
        private _vAligns;
        constructor();
        setCellWidth(indexOrComponent: number | AComponent, cellHeight: number): void;
        getCellWidth(indexOrComponent: number | AComponent): number;
        setCellHAlign(indexOrComponent: number | AComponent, hAlign: EHAlign): void;
        getCellHAlign(indexOrComponent: number | AComponent): EHAlign;
        setCellVAlign(indexOrComponent: number | AComponent, vAlign: EVAlign): void;
        getCellVAlign(indexOrComponent: number | AComponent): EVAlign;
        setLastCellHAlign(hAlign: EHAlign): void;
        setLastCellVAlign(vAlign: EVAlign): void;
        setLastCellWidth(width: number): void;
        addEmptyCell(width: number): void;
        _onChildAdded(child: AComponent): void;
        _onChildRemoved(child: AComponent, index: number): void;
        _onChildrenCleared(): void;
        protected onLayout(): void;
        private setInList<T>(list, index, value);
        private getFromList<T>(list, index);
        private removeFromList<T>(list, index);
        children: LayoutChildren;
        Height: NumberProperty;
        height: number;
    }
}
declare namespace cubee {
    class VBox extends ALayout {
        private _width;
        private _cellHeights;
        private _hAligns;
        private _vAligns;
        constructor();
        children: LayoutChildren;
        setCellHeight(indexOrComponent: number | AComponent, cellHeight: number): void;
        private setInList<T>(list, index, value);
        private getFromList<T>(list, index);
        private removeFromList<T>(list, index);
        getCellHeight(indexOrComponent: number | AComponent): number;
        setCellHAlign(indexOrComponent: number | AComponent, hAlign: EHAlign): void;
        getCellHAlign(indexOrComponent: number | AComponent): EHAlign;
        setCellVAlign(indexOrComponent: number | AComponent, vAlign: EVAlign): void;
        getCellVAlign(indexOrComponent: number | AComponent): EVAlign;
        setLastCellHAlign(hAlign: EHAlign): void;
        setLastCellVAlign(vAlign: EVAlign): void;
        setLastCellHeight(height: number): void;
        addEmptyCell(height: number): void;
        Width: NumberProperty;
        width: number;
        _onChildAdded(child: AComponent): void;
        _onChildRemoved(child: AComponent, index: number): void;
        _onChildrenCleared(): void;
        protected onLayout(): void;
    }
}
declare namespace cubee {
    class ScrollBox extends AUserControl {
        private _content;
        private _hScrollPolicy;
        private _vScrollPolicy;
        private _scrollWidth;
        private _scrollHeight;
        private _hScrollPos;
        private _vScrollPos;
        private _maxHScrollPos;
        private _maxVScrollPos;
        private _maxHScrollPosWriter;
        private _maxVScrollPosWriter;
        private _calculateScrollWidthExp;
        private _calculateScrollHeightExp;
        constructor();
        protected widthProperty(): NumberProperty;
        Width: NumberProperty;
        width: number;
        protected heightProperty(): NumberProperty;
        Height: NumberProperty;
        height: number;
        Content: Property<AComponent>;
        content: AComponent;
        HScrollPolicy: Property<EScrollBarPolicy>;
        hScrollPolicy: EScrollBarPolicy;
        VScrollPolicy: Property<EScrollBarPolicy>;
        vScrollPolicy: EScrollBarPolicy;
        ScrollWidth: NumberProperty;
        scrollWidth: number;
        ScrollHeight: NumberProperty;
        scrollHeight: number;
        HScrollPos: NumberProperty;
        hScrollPos: number;
        VScrollPos: NumberProperty;
        vScrollPos: number;
        MaxHScrollPos: NumberProperty;
        maxHScrollPos: number;
        MaxVScrollPos: NumberProperty;
        maxVScrollPos: number;
    }
}
declare namespace cubee {
    class Label extends AComponent {
        private _width;
        private _height;
        private _text;
        private _textOverflow;
        private _foreColor;
        private _textAlign;
        private _verticalAlign;
        private _bold;
        private _italic;
        private _underline;
        private _fontSize;
        private _fontFamily;
        constructor();
        Width: NumberProperty;
        width: number;
        Height: NumberProperty;
        height: number;
        Text: StringProperty;
        text: string;
        TextOverflow: Property<ETextOverflow>;
        textOverflow: ETextOverflow;
        ForeColor: ColorProperty;
        foreColor: Color;
        VerticalAlign: Property<EVAlign>;
        verticalAlign: EVAlign;
        Bold: BooleanProperty;
        bold: boolean;
        Italic: BooleanProperty;
        italic: boolean;
        Underline: BooleanProperty;
        underline: boolean;
        TextAlign: Property<ETextAlign>;
        textAlign: ETextAlign;
        FontSize: NumberProperty;
        fontSize: number;
        FontFamily: Property<FontFamily>;
        fontFamily: FontFamily;
    }
}
declare namespace cubee {
    class Button extends AComponent {
        private _width;
        private _height;
        private _text;
        private _textOverflow;
        private _foreColor;
        private _textAlign;
        private _verticalAlign;
        private _bold;
        private _italic;
        private _underline;
        private _fontSize;
        private _fontFamily;
        private _background;
        private _shadow;
        constructor();
        Width: NumberProperty;
        width: number;
        Height: NumberProperty;
        height: number;
        Text: StringProperty;
        text: string;
        TextOverflow: Property<ETextOverflow>;
        textOverflow: ETextOverflow;
        ForeColor: ColorProperty;
        foreColor: Color;
        VerticalAlign: Property<EVAlign>;
        verticalAlign: EVAlign;
        Bold: BooleanProperty;
        bold: boolean;
        Italic: BooleanProperty;
        italic: boolean;
        Underline: BooleanProperty;
        underline: boolean;
        TextAlign: Property<ETextAlign>;
        textAlign: ETextAlign;
        FontSize: NumberProperty;
        fontSize: number;
        FontFamily: Property<FontFamily>;
        fontFamily: FontFamily;
        Background: BackgroundProperty;
        background: ABackground;
        Shadow: Property<BoxShadow>;
        shadow: BoxShadow;
    }
}
declare namespace cubee {
    class TextBox extends AComponent {
        private _width;
        private _height;
        private _text;
        private _background;
        private _foreColor;
        private _textAlign;
        private _verticalAlign;
        private _bold;
        private _italic;
        private _underline;
        private _fontSize;
        private _fontFamily;
        private _placeholder;
        constructor();
        Width: NumberProperty;
        width: number;
        Height: NumberProperty;
        height: number;
        Text: StringProperty;
        text: string;
        Background: BackgroundProperty;
        background: ABackground;
        ForeColor: ColorProperty;
        foreColor: Color;
        TextAlign: Property<ETextAlign>;
        textAlign: ETextAlign;
        VerticalAlign: Property<EVAlign>;
        verticalAlign: EVAlign;
        Bold: BooleanProperty;
        bold: boolean;
        Italic: BooleanProperty;
        italic: boolean;
        Underline: BooleanProperty;
        underline: boolean;
        FontSize: NumberProperty;
        fontSize: number;
        FontFamily: Property<FontFamily>;
        fontFamily: FontFamily;
        Placeholder: StringProperty;
        placeholder: string;
    }
}
declare namespace cubee {
    class PasswordBox extends AComponent {
        private _width;
        private _height;
        private _text;
        private _background;
        private _foreColor;
        private _textAlign;
        private _verticalAlign;
        private _bold;
        private _italic;
        private _underline;
        private _fontSize;
        private _fontFamily;
        private _placeholder;
        constructor();
        Width: NumberProperty;
        width: number;
        Height: NumberProperty;
        height: number;
        Text: StringProperty;
        text: string;
        Background: BackgroundProperty;
        background: ABackground;
        ForeColor: ColorProperty;
        foreColor: Color;
        TextAlign: Property<ETextAlign>;
        textAlign: ETextAlign;
        VerticalAlign: Property<EVAlign>;
        verticalAlign: EVAlign;
        Bold: BooleanProperty;
        bold: boolean;
        Italic: BooleanProperty;
        italic: boolean;
        Underline: BooleanProperty;
        underline: boolean;
        FontSize: NumberProperty;
        fontSize: number;
        FontFamily: Property<FontFamily>;
        fontFamily: FontFamily;
        Placeholder: StringProperty;
        placeholder: string;
    }
}
declare namespace cubee {
    class TextArea extends AComponent {
        private _width;
        private _height;
        private _text;
        private _background;
        private _foreColor;
        private _textAlign;
        private _verticalAlign;
        private _bold;
        private _italic;
        private _underline;
        private _fontSize;
        private _fontFamily;
        private _placeholder;
        constructor();
        Width: NumberProperty;
        width: number;
        Height: NumberProperty;
        height: number;
        Text: StringProperty;
        text: string;
        Background: BackgroundProperty;
        background: ABackground;
        ForeColor: ColorProperty;
        foreColor: Color;
        TextAlign: Property<ETextAlign>;
        textAlign: ETextAlign;
        VerticalAlign: Property<EVAlign>;
        verticalAlign: EVAlign;
        Bold: BooleanProperty;
        bold: boolean;
        Italic: BooleanProperty;
        italic: boolean;
        Underline: BooleanProperty;
        underline: boolean;
        FontSize: NumberProperty;
        fontSize: number;
        FontFamily: Property<FontFamily>;
        fontFamily: FontFamily;
        Placeholder: StringProperty;
        placeholder: string;
    }
}
declare namespace cubee {
    class CheckBox extends AComponent {
        private _checked;
        constructor();
        Checked: BooleanProperty;
        checked: boolean;
    }
}
declare namespace cubee {
    class ComboBox<T> extends AComponent {
        private _selectedIndex;
        private _selectedItem;
        private items;
        private _width;
        private _height;
        private _text;
        private _background;
        private _foreColor;
        private _textAlign;
        private _verticalAlign;
        private _bold;
        private _italic;
        private _underline;
        private _fontSize;
        private _fontFamily;
        private _placeholder;
        constructor();
        Width: NumberProperty;
        width: number;
        Height: NumberProperty;
        height: number;
        Text: StringProperty;
        text: string;
        Background: BackgroundProperty;
        background: ABackground;
        ForeColor: ColorProperty;
        foreColor: Color;
        TextAlign: Property<ETextAlign>;
        textAlign: ETextAlign;
        VerticalAlign: Property<EVAlign>;
        verticalAlign: EVAlign;
        Bold: BooleanProperty;
        bold: boolean;
        Italic: BooleanProperty;
        italic: boolean;
        Underline: BooleanProperty;
        underline: boolean;
        FontSize: NumberProperty;
        fontSize: number;
        FontFamily: Property<FontFamily>;
        fontFamily: FontFamily;
        Placeholder: StringProperty;
        placeholder: string;
        protected selectedIndexProperty(): NumberProperty;
        SelectedIndex: NumberProperty;
        selectedIndex: number;
        protected selectedItemProperty(): Property<T>;
        SelectedItem: Property<T>;
        selectedItem: T;
    }
}
declare namespace cubee {
    class PictureBox extends AComponent {
        private _width;
        private _height;
        private _pictureSizeMode;
        private _image;
        private _background;
        private _imgElement;
        constructor();
        private recalculateSize();
        protected pictureSizeModeProperty(): Property<EPictureSizeMode>;
        PictureSizeMode: Property<EPictureSizeMode>;
        pictureSizeMode: EPictureSizeMode;
        protected widthProperty(): NumberProperty;
        Width: NumberProperty;
        width: number;
        protected heightProperty(): NumberProperty;
        Height: NumberProperty;
        height: number;
        protected paddingProperty(): PaddingProperty;
        Padding: PaddingProperty;
        padding: Padding;
        protected borderProperty(): BorderProperty;
        Border: BorderProperty;
        border: Border;
        protected backgroundProperty(): BackgroundProperty;
        Background: BackgroundProperty;
        background: ABackground;
        protected imageProperty(): Property<Image>;
        Image: Property<Image>;
        image: Image;
    }
}
declare namespace cubee {
    class APopup {
        private _modal;
        private _autoClose;
        private _glassColor;
        private _translateX;
        private _translateY;
        private _center;
        private _popupRoot;
        private _rootComponentContainer;
        private _rootComponent;
        private _visible;
        constructor(modal?: boolean, autoClose?: boolean, glassColor?: Color);
        __popupRoot: Panel;
        protected rootComponent: AComponent;
        protected show(): void;
        protected close(): boolean;
        protected isCloseAllowed(): boolean;
        protected onClosed(): void;
        modal: boolean;
        autoClose: boolean;
        glassColor: Color;
        TranslateX: NumberProperty;
        translateX: number;
        TranslateY: NumberProperty;
        translateY: number;
        Center: BooleanProperty;
        center: boolean;
        _layout(): void;
    }
    class Popups {
        private static _popups;
        private static _layoutRunOnce;
        static _addPopup(popup: APopup): void;
        static _removePopup(popup: APopup): void;
        static _requestLayout(): void;
        private static layout();
        constructor();
    }
}
declare namespace cubee {
    class CubeePanel {
        private _layoutRunOnce;
        private _contentPanel;
        private _rootComponent;
        private _element;
        private _left;
        private _top;
        private _clientWidth;
        private _clientHeight;
        private _offsetWidth;
        private _offsetHeight;
        constructor(element: HTMLDivElement);
        private checkBounds();
        requestLayout(): void;
        layout(): void;
        rootComponent: AComponent;
        ClientWidth: NumberProperty;
        clientWidth: number;
        ClientHeight: NumberProperty;
        clientHeight: number;
        BoundsWidth: NumberProperty;
        boundsWidth: number;
        BoundsHeight: NumberProperty;
        boundsHeight: number;
        BoundsLeft: NumberProperty;
        boundsLeft: number;
        BoundsTop: NumberProperty;
        boundsTop: number;
    }
}
declare namespace cubee {
    class EIcon {
        private _value;
        private static __500PX;
        static _500PX: EIcon;
        private static _AMAZON;
        static AMAZON: EIcon;
        private static _BALANCE_SCALE;
        static BALANCE_SCALE: EIcon;
        private static _BATTERY_0;
        static BATTERY_0: EIcon;
        private static _BATTERY_1;
        static BATTERY_1: EIcon;
        private static _BATTERY_2;
        static BATTERY_2: EIcon;
        private static _BATTERY_3;
        static BATTERY_3: EIcon;
        private static _BATTERY_4;
        static BATTERY_4: EIcon;
        private static _BATTERY_EMPTY;
        static BATTERY_EMPTY: EIcon;
        private static _BATTERY_FULL;
        static BATTERY_FULL: EIcon;
        private static _BATTERY_HALF;
        static BATTERY_HALF: EIcon;
        private static _BATTERY_QUARTER;
        static BATTERY_QUARTER: EIcon;
        private static _BATTERY_THREE_QUARTERS;
        static BATTERY_THREE_QUARTERS: EIcon;
        private static _BLACK_TIE;
        static BLACK_TIE: EIcon;
        private static _CALENDAR_CHECK_O;
        static CALENDAR_CHECK_O: EIcon;
        private static _CALENDAR_MINUS_O;
        static CALENDAR_MINUS_O: EIcon;
        private static _CALENDAR_PLUS_O;
        static CALENDAR_PLUS_O: EIcon;
        private static _CALENDAR_TIMES_O;
        static CALENDAR_TIMES_O: EIcon;
        private static _CC_DINERS_CLUB;
        static CC_DINERS_CLUB: EIcon;
        private static _CC_JCB;
        static CC_JCB: EIcon;
        private static _CHROME;
        static CHROME: EIcon;
        private static _CLONE;
        static CLONE: EIcon;
        private static _COMMENTING;
        static COMMENTING: EIcon;
        private static _COMMENTING_O;
        static COMMENTING_O: EIcon;
        private static _CONTAO;
        static CONTAO: EIcon;
        private static _CREATIVE_COMMONS;
        static CREATIVE_COMMONS: EIcon;
        private static _EXPEDITEDSSL;
        static EXPEDITEDSSL: EIcon;
        private static _FIREFOX;
        static FIREFOX: EIcon;
        private static _FONTICONS;
        static FONTICONS: EIcon;
        private static _GENDERLESS;
        static GENDERLESS: EIcon;
        private static _GET_POCKET;
        static GET_POCKET: EIcon;
        private static _GG;
        static GG: EIcon;
        private static _GG_CIRCLE;
        static GG_CIRCLE: EIcon;
        private static _HAND_GRAB_O;
        static HAND_GRAB_O: EIcon;
        private static _HAND_LIZARD_O;
        static HAND_LIZARD_O: EIcon;
        private static _HAND_PAPER_O;
        static HAND_PAPER_O: EIcon;
        private static _HAND_PEACE_O;
        static HAND_PEACE_O: EIcon;
        private static _HAND_POINTER_O;
        static HAND_POINTER_O: EIcon;
        private static _HAND_ROCK_O;
        static HAND_ROCK_O: EIcon;
        private static _HAND_SCISSORS_O;
        static HAND_SCISSORS_O: EIcon;
        private static _HAND_SPOCK_O;
        static HAND_SPOCK_O: EIcon;
        private static _HAND_STOP_O;
        static HAND_STOP_O: EIcon;
        private static _HOURGLASS;
        static HOURGLASS: EIcon;
        private static _HOURGLASS_1;
        static HOURGLASS_1: EIcon;
        private static _HOURGLASS_2;
        static HOURGLASS_2: EIcon;
        private static _HOURGLASS_3;
        static HOURGLASS_3: EIcon;
        private static _HOURGLASS_END;
        static HOURGLASS_END: EIcon;
        private static _HOURGLASS_HALF;
        static HOURGLASS_HALF: EIcon;
        private static _HOURGLASS_O;
        static HOURGLASS_O: EIcon;
        private static _HOURGLASS_START;
        static HOURGLASS_START: EIcon;
        private static _HOUZZ;
        static HOUZZ: EIcon;
        private static _I_CURSOR;
        static I_CURSOR: EIcon;
        private static _INDUSTRY;
        static INDUSTRY: EIcon;
        private static _INTERNET_EXPLORER;
        static INTERNET_EXPLORER: EIcon;
        private static _MAP;
        static MAP: EIcon;
        private static _MAP_O;
        static MAP_O: EIcon;
        private static _MAP_PIN;
        static MAP_PIN: EIcon;
        private static _MAP_SIGNS;
        static MAP_SIGNS: EIcon;
        private static _MOUSE_POINTER;
        static MOUSE_POINTER: EIcon;
        private static _OBJECT_GROUP;
        static OBJECT_GROUP: EIcon;
        private static _OBJECT_UNGROUP;
        static OBJECT_UNGROUP: EIcon;
        private static _ODNOKLASSNIKI;
        static ODNOKLASSNIKI: EIcon;
        private static _ODNOKLASSNIKI_SQUARE;
        static ODNOKLASSNIKI_SQUARE: EIcon;
        private static _OPENCART;
        static OPENCART: EIcon;
        private static _OPERA;
        static OPERA: EIcon;
        private static _OPTIN_MONSTER;
        static OPTIN_MONSTER: EIcon;
        private static _REGISTERED;
        static REGISTERED: EIcon;
        private static _SAFARI;
        static SAFARI: EIcon;
        private static _STICKY_NOTE;
        static STICKY_NOTE: EIcon;
        private static _STICKY_NOTE_O;
        static STICKY_NOTE_O: EIcon;
        private static _TELEVISION;
        static TELEVISION: EIcon;
        private static _TRADEMARK;
        static TRADEMARK: EIcon;
        private static _TRIPADVISOR;
        static TRIPADVISOR: EIcon;
        private static _TV;
        static TV: EIcon;
        private static _VIMEO;
        static VIMEO: EIcon;
        private static _WIKIPEDIA_W;
        static WIKIPEDIA_W: EIcon;
        private static _Y_COMBINATOR;
        static Y_COMBINATOR: EIcon;
        private static _YC;
        static YC: EIcon;
        private static _ADJUST;
        static ADJUST: EIcon;
        private static _ANCHOR;
        static ANCHOR: EIcon;
        private static _ARCHIVE;
        static ARCHIVE: EIcon;
        private static _AREA_CHART;
        static AREA_CHART: EIcon;
        private static _ARROWS;
        static ARROWS: EIcon;
        private static _ARROWS_H;
        static ARROWS_H: EIcon;
        private static _ARROWS_V;
        static ARROWS_V: EIcon;
        private static _ASTERISK;
        static ASTERISK: EIcon;
        private static _AT;
        static AT: EIcon;
        private static _AUTOMOBILE;
        static AUTOMOBILE: EIcon;
        private static _BAN;
        static BAN: EIcon;
        private static _BANK;
        static BANK: EIcon;
        private static _BAR_CHART;
        static BAR_CHART: EIcon;
        private static _BAR_CHART_O;
        static BAR_CHART_O: EIcon;
        private static _BARCODE;
        static BARCODE: EIcon;
        private static _BARS;
        static BARS: EIcon;
        private static _BED;
        static BED: EIcon;
        private static _BEER;
        static BEER: EIcon;
        private static _BELL;
        static BELL: EIcon;
        private static _BELL_O;
        static BELL_O: EIcon;
        private static _BELL_SLASH;
        static BELL_SLASH: EIcon;
        private static _BELL_SLASH_O;
        static BELL_SLASH_O: EIcon;
        private static _BICYCLE;
        static BICYCLE: EIcon;
        private static _BINOCULARS;
        static BINOCULARS: EIcon;
        private static _BIRTHDAY_CAKE;
        static BIRTHDAY_CAKE: EIcon;
        private static _BOLT;
        static BOLT: EIcon;
        private static _BOMB;
        static BOMB: EIcon;
        private static _BOOK;
        static BOOK: EIcon;
        private static _BOOKMARK;
        static BOOKMARK: EIcon;
        private static _BOOKMARK_O;
        static BOOKMARK_O: EIcon;
        private static _BRIEFCASE;
        static BRIEFCASE: EIcon;
        private static _BUG;
        static BUG: EIcon;
        private static _BUILDING;
        static BUILDING: EIcon;
        private static _BUILDING_O;
        static BUILDING_O: EIcon;
        private static _BULLHORN;
        static BULLHORN: EIcon;
        private static _BULLSEYE;
        static BULLSEYE: EIcon;
        private static _BUS;
        static BUS: EIcon;
        private static _CAB;
        static CAB: EIcon;
        private static _CALCULATOR;
        static CALCULATOR: EIcon;
        private static _CALENDAR;
        static CALENDAR: EIcon;
        private static _CAMERA;
        static CAMERA: EIcon;
        private static _CAMERA_RETRO;
        static CAMERA_RETRO: EIcon;
        private static _CAR;
        static CAR: EIcon;
        private static _CARET_SQUARE_O_DOWN;
        static CARET_SQUARE_O_DOWN: EIcon;
        private static _CARET_SQUARE_O_LEFT;
        static CARET_SQUARE_O_LEFT: EIcon;
        private static _CARET_SQUARE_O_RIGHT;
        static CARET_SQUARE_O_RIGHT: EIcon;
        private static _CARET_SQUARE_O_UP;
        static CARET_SQUARE_O_UP: EIcon;
        private static _CART_ARROW_DOWN;
        static CART_ARROW_DOWN: EIcon;
        private static _CART_PLUS;
        static CART_PLUS: EIcon;
        private static _CC;
        static CC: EIcon;
        private static _CERTIFICATE;
        static CERTIFICATE: EIcon;
        private static _CHECK;
        static CHECK: EIcon;
        private static _CHECK_CIRCLE;
        static CHECK_CIRCLE: EIcon;
        private static _CHECK_CIRCLE_O;
        static CHECK_CIRCLE_O: EIcon;
        private static _CHECK_SQUARE;
        static CHECK_SQUARE: EIcon;
        private static _CHECK_SQUARE_O;
        static CHECK_SQUARE_O: EIcon;
        private static _CHILD;
        static CHILD: EIcon;
        private static _CIRCLE;
        static CIRCLE: EIcon;
        private static _CIRCLE_O;
        static CIRCLE_O: EIcon;
        private static _CIRCLE_O_NOTCH;
        static CIRCLE_O_NOTCH: EIcon;
        private static _CIRCLE_THIN;
        static CIRCLE_THIN: EIcon;
        private static _CLOCK_O;
        static CLOCK_O: EIcon;
        private static _CLOSE;
        static CLOSE: EIcon;
        private static _CLOUD;
        static CLOUD: EIcon;
        private static _CLOUD_DOWNLOAD;
        static CLOUD_DOWNLOAD: EIcon;
        private static _CLOUD_UPLOAD;
        static CLOUD_UPLOAD: EIcon;
        private static _CODE;
        static CODE: EIcon;
        private static _CODE_FORK;
        static CODE_FORK: EIcon;
        private static _COFFEE;
        static COFFEE: EIcon;
        private static _COG;
        static COG: EIcon;
        private static _COGS;
        static COGS: EIcon;
        private static _COMMENT;
        static COMMENT: EIcon;
        private static _COMMENT_O;
        static COMMENT_O: EIcon;
        private static _COMMENTS;
        static COMMENTS: EIcon;
        private static _COMMENTS_O;
        static COMMENTS_O: EIcon;
        private static _COMPASS;
        static COMPASS: EIcon;
        private static _COPYRIGHT;
        static COPYRIGHT: EIcon;
        private static _CREDIT_CARD;
        static CREDIT_CARD: EIcon;
        private static _CROP;
        static CROP: EIcon;
        private static _CROSSHAIRS;
        static CROSSHAIRS: EIcon;
        private static _CUBE;
        static CUBE: EIcon;
        private static _CUBES;
        static CUBES: EIcon;
        private static _CUTLERY;
        static CUTLERY: EIcon;
        private static _DASHBOARD;
        static DASHBOARD: EIcon;
        private static _DATABASE;
        static DATABASE: EIcon;
        private static _DESKTOP;
        static DESKTOP: EIcon;
        private static _DIAMOND;
        static DIAMOND: EIcon;
        private static _DOT_CIRCLE_O;
        static DOT_CIRCLE_O: EIcon;
        private static _DOWNLOAD;
        static DOWNLOAD: EIcon;
        private static _EDIT;
        static EDIT: EIcon;
        private static _ELLIPSIS_H;
        static ELLIPSIS_H: EIcon;
        private static _ELLIPSIS_V;
        static ELLIPSIS_V: EIcon;
        private static _ENVELOPE;
        static ENVELOPE: EIcon;
        private static _ENVELOPE_O;
        static ENVELOPE_O: EIcon;
        private static _ENVELOPE_SQUARE;
        static ENVELOPE_SQUARE: EIcon;
        private static _ERASER;
        static ERASER: EIcon;
        private static _EXCHANGE;
        static EXCHANGE: EIcon;
        private static _EXCLAMATION;
        static EXCLAMATION: EIcon;
        private static _EXCLAMATION_CIRCLE;
        static EXCLAMATION_CIRCLE: EIcon;
        private static _EXCLAMATION_TRIANGLE;
        static EXCLAMATION_TRIANGLE: EIcon;
        private static _EXTERNAL_LINK;
        static EXTERNAL_LINK: EIcon;
        private static _EXTERNAL_LINK_SQUARE;
        static EXTERNAL_LINK_SQUARE: EIcon;
        private static _EYE;
        static EYE: EIcon;
        private static _EYE_SLASH;
        static EYE_SLASH: EIcon;
        private static _EYEDROPPER;
        static EYEDROPPER: EIcon;
        private static _FAX;
        static FAX: EIcon;
        private static _FEED;
        static FEED: EIcon;
        private static _FEMALE;
        static FEMALE: EIcon;
        private static _FIGHTER_JET;
        static FIGHTER_JET: EIcon;
        private static _FILE_ARCHIVE_O;
        static FILE_ARCHIVE_O: EIcon;
        private static _FILE_AUDIO_O;
        static FILE_AUDIO_O: EIcon;
        private static _FILE_CODE_O;
        static FILE_CODE_O: EIcon;
        private static _FILE_EXCEL_O;
        static FILE_EXCEL_O: EIcon;
        private static _FILE_IMAGE_O;
        static FILE_IMAGE_O: EIcon;
        private static _FILE_MOVIE_O;
        static FILE_MOVIE_O: EIcon;
        private static _FILE_PDF_O;
        static FILE_PDF_O: EIcon;
        private static _FILE_PHOTO_O;
        static FILE_PHOTO_O: EIcon;
        private static _FILE_PICTURE_O;
        static FILE_PICTURE_O: EIcon;
        private static _FILE_POWERPOINT_O;
        static FILE_POWERPOINT_O: EIcon;
        private static _FILE_SOUND_O;
        static FILE_SOUND_O: EIcon;
        private static _FILE_VIDEO_O;
        static FILE_VIDEO_O: EIcon;
        private static _FILE_WORD_O;
        static FILE_WORD_O: EIcon;
        private static _FILE_ZIP_O;
        static FILE_ZIP_O: EIcon;
        private static _FILM;
        static FILM: EIcon;
        private static _FILTER;
        static FILTER: EIcon;
        private static _FIRE;
        static FIRE: EIcon;
        private static _FIRE_EXTINGUISHER;
        static FIRE_EXTINGUISHER: EIcon;
        private static _FLAG;
        static FLAG: EIcon;
        private static _FLAG_CHECKERED;
        static FLAG_CHECKERED: EIcon;
        private static _FLAG_O;
        static FLAG_O: EIcon;
        private static _FLASH;
        static FLASH: EIcon;
        private static _FLASK;
        static FLASK: EIcon;
        private static _FOLDER;
        static FOLDER: EIcon;
        private static _FOLDER_O;
        static FOLDER_O: EIcon;
        private static _FOLDER_OPEN;
        static FOLDER_OPEN: EIcon;
        private static _FOLDER_OPEN_O;
        static FOLDER_OPEN_O: EIcon;
        private static _FROWN_O;
        static FROWN_O: EIcon;
        private static _FUTBOL_O;
        static FUTBOL_O: EIcon;
        private static _GAMEPAD;
        static GAMEPAD: EIcon;
        private static _GAVEL;
        static GAVEL: EIcon;
        private static _GEAR;
        static GEAR: EIcon;
        private static _GEARS;
        static GEARS: EIcon;
        private static _GIFT;
        static GIFT: EIcon;
        private static _GLASS;
        static GLASS: EIcon;
        private static _GLOBE;
        static GLOBE: EIcon;
        private static _GRADUATION_CAP;
        static GRADUATION_CAP: EIcon;
        private static _GROUP;
        static GROUP: EIcon;
        private static _HDD_O;
        static HDD_O: EIcon;
        private static _HEADPHONES;
        static HEADPHONES: EIcon;
        private static _HEART;
        static HEART: EIcon;
        private static _HEART_O;
        static HEART_O: EIcon;
        private static _HEARTBEAT;
        static HEARTBEAT: EIcon;
        private static _HISTORY;
        static HISTORY: EIcon;
        private static _HOME;
        static HOME: EIcon;
        private static _HOTEL;
        static HOTEL: EIcon;
        private static _IMAGE;
        static IMAGE: EIcon;
        private static _INBOX;
        static INBOX: EIcon;
        private static _INFO;
        static INFO: EIcon;
        private static _INFO_CIRCLE;
        static INFO_CIRCLE: EIcon;
        private static _INSTITUTION;
        static INSTITUTION: EIcon;
        private static _KEY;
        static KEY: EIcon;
        private static _KEYBOARD_O;
        static KEYBOARD_O: EIcon;
        private static _LANGUAGE;
        static LANGUAGE: EIcon;
        private static _LAPTOP;
        static LAPTOP: EIcon;
        private static _LEAF;
        static LEAF: EIcon;
        private static _LEGAL;
        static LEGAL: EIcon;
        private static _LEMON_O;
        static LEMON_O: EIcon;
        private static _LEVEL_DOWN;
        static LEVEL_DOWN: EIcon;
        private static _LEVEL_UP;
        static LEVEL_UP: EIcon;
        private static _LIFE_BOUY;
        static LIFE_BOUY: EIcon;
        private static _LIFE_BUOY;
        static LIFE_BUOY: EIcon;
        private static _LIFE_RING;
        static LIFE_RING: EIcon;
        private static _LIFE_SAVER;
        static LIFE_SAVER: EIcon;
        private static _LIGHTBULB_O;
        static LIGHTBULB_O: EIcon;
        private static _LINE_CHART;
        static LINE_CHART: EIcon;
        private static _LOCATION_ARROW;
        static LOCATION_ARROW: EIcon;
        private static _LOCK;
        static LOCK: EIcon;
        private static _MAGIC;
        static MAGIC: EIcon;
        private static _MAGNET;
        static MAGNET: EIcon;
        private static _MAIL_FORWARD;
        static MAIL_FORWARD: EIcon;
        private static _MAIL_REPLY;
        static MAIL_REPLY: EIcon;
        private static _MAIL_REPLY_ALL;
        static MAIL_REPLY_ALL: EIcon;
        private static _MALE;
        static MALE: EIcon;
        private static _MAP_MARKER;
        static MAP_MARKER: EIcon;
        private static _MEH_O;
        static MEH_O: EIcon;
        private static _MICROPHONE;
        static MICROPHONE: EIcon;
        private static _MICROPHONE_SLASH;
        static MICROPHONE_SLASH: EIcon;
        private static _MINUS;
        static MINUS: EIcon;
        private static _MINUS_CIRCLE;
        static MINUS_CIRCLE: EIcon;
        private static _MINUS_SQUARE;
        static MINUS_SQUARE: EIcon;
        private static _MINUS_SQUARE_O;
        static MINUS_SQUARE_O: EIcon;
        private static _MOBILE;
        static MOBILE: EIcon;
        private static _MOBILE_PHONE;
        static MOBILE_PHONE: EIcon;
        private static _MONEY;
        static MONEY: EIcon;
        private static _MOON_O;
        static MOON_O: EIcon;
        private static _MORTAR_BOARD;
        static MORTAR_BOARD: EIcon;
        private static _MOTORCYCLE;
        static MOTORCYCLE: EIcon;
        private static _MUSIC;
        static MUSIC: EIcon;
        private static _NAVICON;
        static NAVICON: EIcon;
        private static _NEWSPAPER_O;
        static NEWSPAPER_O: EIcon;
        private static _PAINT_BRUSH;
        static PAINT_BRUSH: EIcon;
        private static _PAPER_PLANE;
        static PAPER_PLANE: EIcon;
        private static _PAPER_PLANE_O;
        static PAPER_PLANE_O: EIcon;
        private static _PAW;
        static PAW: EIcon;
        private static _PENCIL;
        static PENCIL: EIcon;
        private static _PENCIL_SQUARE;
        static PENCIL_SQUARE: EIcon;
        private static _PENCIL_SQUARE_O;
        static PENCIL_SQUARE_O: EIcon;
        private static _PHONE;
        static PHONE: EIcon;
        private static _PHONE_SQUARE;
        static PHONE_SQUARE: EIcon;
        private static _PHOTO;
        static PHOTO: EIcon;
        private static _PICTURE_O;
        static PICTURE_O: EIcon;
        private static _PIE_CHART;
        static PIE_CHART: EIcon;
        private static _PLANE;
        static PLANE: EIcon;
        private static _PLUG;
        static PLUG: EIcon;
        private static _PLUS;
        static PLUS: EIcon;
        private static _PLUS_CIRCLE;
        static PLUS_CIRCLE: EIcon;
        private static _PLUS_SQUARE;
        static PLUS_SQUARE: EIcon;
        private static _PLUS_SQUARE_O;
        static PLUS_SQUARE_O: EIcon;
        private static _POWER_OFF;
        static POWER_OFF: EIcon;
        private static _PRINT;
        static PRINT: EIcon;
        private static _PUZZLE_PIECE;
        static PUZZLE_PIECE: EIcon;
        private static _QRCODE;
        static QRCODE: EIcon;
        private static _QUESTION;
        static QUESTION: EIcon;
        private static _QUESTION_CIRCLE;
        static QUESTION_CIRCLE: EIcon;
        private static _QUOTE_LEFT;
        static QUOTE_LEFT: EIcon;
        private static _QUOTE_RIGHT;
        static QUOTE_RIGHT: EIcon;
        private static _RANDOM;
        static RANDOM: EIcon;
        private static _RECYCLE;
        static RECYCLE: EIcon;
        private static _REFRESH;
        static REFRESH: EIcon;
        private static _REMOVE;
        static REMOVE: EIcon;
        private static _REORDER;
        static REORDER: EIcon;
        private static _REPLY;
        static REPLY: EIcon;
        private static _REPLY_ALL;
        static REPLY_ALL: EIcon;
        private static _RETWEET;
        static RETWEET: EIcon;
        private static _ROAD;
        static ROAD: EIcon;
        private static _ROCKET;
        static ROCKET: EIcon;
        private static _RSS;
        static RSS: EIcon;
        private static _RSS_SQUARE;
        static RSS_SQUARE: EIcon;
        private static _SEARCH;
        static SEARCH: EIcon;
        private static _SEARCH_MINUS;
        static SEARCH_MINUS: EIcon;
        private static _SEARCH_PLUS;
        static SEARCH_PLUS: EIcon;
        private static _SEND;
        static SEND: EIcon;
        private static _SEND_O;
        static SEND_O: EIcon;
        private static _SERVER;
        static SERVER: EIcon;
        private static _SHARE;
        static SHARE: EIcon;
        private static _SHARE_ALT;
        static SHARE_ALT: EIcon;
        private static _SHARE_ALT_SQUARE;
        static SHARE_ALT_SQUARE: EIcon;
        private static _SHARE_SQUARE;
        static SHARE_SQUARE: EIcon;
        private static _SHARE_SQUARE_O;
        static SHARE_SQUARE_O: EIcon;
        private static _SHIELD;
        static SHIELD: EIcon;
        private static _SHIP;
        static SHIP: EIcon;
        private static _SHOPPING_CART;
        static SHOPPING_CART: EIcon;
        private static _SIGN_IN;
        static SIGN_IN: EIcon;
        private static _SIGN_OUT;
        static SIGN_OUT: EIcon;
        private static _SIGNAL;
        static SIGNAL: EIcon;
        private static _SITEMAP;
        static SITEMAP: EIcon;
        private static _SLIDERS;
        static SLIDERS: EIcon;
        private static _SMILE_O;
        static SMILE_O: EIcon;
        private static _SOCCER_BALL_O;
        static SOCCER_BALL_O: EIcon;
        private static _SORT;
        static SORT: EIcon;
        private static _SORT_ALPHA_ASC;
        static SORT_ALPHA_ASC: EIcon;
        private static _SORT_ALPHA_DESC;
        static SORT_ALPHA_DESC: EIcon;
        private static _SORT_AMOUNT_ASC;
        static SORT_AMOUNT_ASC: EIcon;
        private static _SORT_AMOUNT_DESC;
        static SORT_AMOUNT_DESC: EIcon;
        private static _SORT_ASC;
        static SORT_ASC: EIcon;
        private static _SORT_DESC;
        static SORT_DESC: EIcon;
        private static _SORT_DOWN;
        static SORT_DOWN: EIcon;
        private static _SORT_NUMERIC_ASC;
        static SORT_NUMERIC_ASC: EIcon;
        private static _SORT_NUMERIC_DESC;
        static SORT_NUMERIC_DESC: EIcon;
        private static _SORT_UP;
        static SORT_UP: EIcon;
        private static _SPACE_SHUTTLE;
        static SPACE_SHUTTLE: EIcon;
        private static _SPINNER;
        static SPINNER: EIcon;
        private static _SPOON;
        static SPOON: EIcon;
        private static _SQUARE;
        static SQUARE: EIcon;
        private static _SQUARE_O;
        static SQUARE_O: EIcon;
        private static _STAR;
        static STAR: EIcon;
        private static _STAR_HALF;
        static STAR_HALF: EIcon;
        private static _STAR_HALF_EMPTY;
        static STAR_HALF_EMPTY: EIcon;
        private static _STAR_HALF_FULL;
        static STAR_HALF_FULL: EIcon;
        private static _STAR_HALF_O;
        static STAR_HALF_O: EIcon;
        private static _STAR_O;
        static STAR_O: EIcon;
        private static _STREET_VIEW;
        static STREET_VIEW: EIcon;
        private static _SUITCASE;
        static SUITCASE: EIcon;
        private static _SUN_O;
        static SUN_O: EIcon;
        private static _SUPPORT;
        static SUPPORT: EIcon;
        private static _TABLET;
        static TABLET: EIcon;
        private static _TACHOMETER;
        static TACHOMETER: EIcon;
        private static _TAG;
        static TAG: EIcon;
        private static _TAGS;
        static TAGS: EIcon;
        private static _TASKS;
        static TASKS: EIcon;
        private static _TAXI;
        static TAXI: EIcon;
        private static _TERMINAL;
        static TERMINAL: EIcon;
        private static _THUMB_TACK;
        static THUMB_TACK: EIcon;
        private static _THUMBS_DOWN;
        static THUMBS_DOWN: EIcon;
        private static _THUMBS_O_DOWN;
        static THUMBS_O_DOWN: EIcon;
        private static _THUMBS_O_UP;
        static THUMBS_O_UP: EIcon;
        private static _THUMBS_UP;
        static THUMBS_UP: EIcon;
        private static _TICKET;
        static TICKET: EIcon;
        private static _TIMES;
        static TIMES: EIcon;
        private static _TIMES_CIRCLE;
        static TIMES_CIRCLE: EIcon;
        private static _TIMES_CIRCLE_O;
        static TIMES_CIRCLE_O: EIcon;
        private static _TINT;
        static TINT: EIcon;
        private static _TOGGLE_DOWN;
        static TOGGLE_DOWN: EIcon;
        private static _TOGGLE_LEFT;
        static TOGGLE_LEFT: EIcon;
        private static _TOGGLE_OFF;
        static TOGGLE_OFF: EIcon;
        private static _TOGGLE_ON;
        static TOGGLE_ON: EIcon;
        private static _TOGGLE_RIGHT;
        static TOGGLE_RIGHT: EIcon;
        private static _TOGGLE_UP;
        static TOGGLE_UP: EIcon;
        private static _TRASH;
        static TRASH: EIcon;
        private static _TRASH_O;
        static TRASH_O: EIcon;
        private static _TREE;
        static TREE: EIcon;
        private static _TROPHY;
        static TROPHY: EIcon;
        private static _TRUCK;
        static TRUCK: EIcon;
        private static _TTY;
        static TTY: EIcon;
        private static _UMBRELLA;
        static UMBRELLA: EIcon;
        private static _UNIVERSITY;
        static UNIVERSITY: EIcon;
        private static _UNLOCK;
        static UNLOCK: EIcon;
        private static _UNLOCK_ALT;
        static UNLOCK_ALT: EIcon;
        private static _UNSORTED;
        static UNSORTED: EIcon;
        private static _UPLOAD;
        static UPLOAD: EIcon;
        private static _USER;
        static USER: EIcon;
        private static _USER_PLUS;
        static USER_PLUS: EIcon;
        private static _USER_SECRET;
        static USER_SECRET: EIcon;
        private static _USER_TIMES;
        static USER_TIMES: EIcon;
        private static _USERS;
        static USERS: EIcon;
        private static _VIDEO_CAMERA;
        static VIDEO_CAMERA: EIcon;
        private static _VOLUME_DOWN;
        static VOLUME_DOWN: EIcon;
        private static _VOLUME_OFF;
        static VOLUME_OFF: EIcon;
        private static _VOLUME_UP;
        static VOLUME_UP: EIcon;
        private static _WARNING;
        static WARNING: EIcon;
        private static _WHEELCHAIR;
        static WHEELCHAIR: EIcon;
        private static _WIFI;
        static WIFI: EIcon;
        private static _WRENCH;
        static WRENCH: EIcon;
        private static _HAND_O_DOWN;
        static HAND_O_DOWN: EIcon;
        private static _HAND_O_LEFT;
        static HAND_O_LEFT: EIcon;
        private static _HAND_O_RIGHT;
        static HAND_O_RIGHT: EIcon;
        private static _HAND_O_UP;
        static HAND_O_UP: EIcon;
        private static _AMBULANCE;
        static AMBULANCE: EIcon;
        private static _SUBWAY;
        static SUBWAY: EIcon;
        private static _TRAIN;
        static TRAIN: EIcon;
        private static _INTERSEX;
        static INTERSEX: EIcon;
        private static _MARS;
        static MARS: EIcon;
        private static _MARS_DOUBLE;
        static MARS_DOUBLE: EIcon;
        private static _MARS_STROKE;
        static MARS_STROKE: EIcon;
        private static _MARS_STROKE_H;
        static MARS_STROKE_H: EIcon;
        private static _MARS_STROKE_V;
        static MARS_STROKE_V: EIcon;
        private static _MERCURY;
        static MERCURY: EIcon;
        private static _NEUTER;
        static NEUTER: EIcon;
        private static _TRANSGENDER;
        static TRANSGENDER: EIcon;
        private static _TRANSGENDER_ALT;
        static TRANSGENDER_ALT: EIcon;
        private static _VENUS;
        static VENUS: EIcon;
        private static _VENUS_DOUBLE;
        static VENUS_DOUBLE: EIcon;
        private static _VENUS_MARS;
        static VENUS_MARS: EIcon;
        private static _FILE;
        static FILE: EIcon;
        private static _FILE_O;
        static FILE_O: EIcon;
        private static _FILE_TEXT;
        static FILE_TEXT: EIcon;
        private static _FILE_TEXT_O;
        static FILE_TEXT_O: EIcon;
        private static _CC_AMEX;
        static CC_AMEX: EIcon;
        private static _CC_DISCOVER;
        static CC_DISCOVER: EIcon;
        private static _CC_MASTERCARD;
        static CC_MASTERCARD: EIcon;
        private static _CC_PAYPAL;
        static CC_PAYPAL: EIcon;
        private static _CC_STRIPE;
        static CC_STRIPE: EIcon;
        private static _CC_VISA;
        static CC_VISA: EIcon;
        private static _GOOGLE_WALLET;
        static GOOGLE_WALLET: EIcon;
        private static _PAYPAL;
        static PAYPAL: EIcon;
        private static _BITCOIN;
        static BITCOIN: EIcon;
        private static _BTC;
        static BTC: EIcon;
        private static _CNY;
        static CNY: EIcon;
        private static _DOLLAR;
        static DOLLAR: EIcon;
        private static _EUR;
        static EUR: EIcon;
        private static _EURO;
        static EURO: EIcon;
        private static _GBP;
        static GBP: EIcon;
        private static _ILS;
        static ILS: EIcon;
        private static _INR;
        static INR: EIcon;
        private static _JPY;
        static JPY: EIcon;
        private static _KRW;
        static KRW: EIcon;
        private static _RMB;
        static RMB: EIcon;
        private static _ROUBLE;
        static ROUBLE: EIcon;
        private static _RUB;
        static RUB: EIcon;
        private static _RUBLE;
        static RUBLE: EIcon;
        private static _RUPEE;
        static RUPEE: EIcon;
        private static _SHEKEL;
        static SHEKEL: EIcon;
        private static _SHEQEL;
        static SHEQEL: EIcon;
        private static _TRY;
        static TRY: EIcon;
        private static _TURKISH_LIRA;
        static TURKISH_LIRA: EIcon;
        private static _USD;
        static USD: EIcon;
        private static _WON;
        static WON: EIcon;
        private static _YEN;
        static YEN: EIcon;
        private static _ALIGN_CENTER;
        static ALIGN_CENTER: EIcon;
        private static _ALIGN_JUSTIFY;
        static ALIGN_JUSTIFY: EIcon;
        private static _ALIGN_LEFT;
        static ALIGN_LEFT: EIcon;
        private static _ALIGN_RIGHT;
        static ALIGN_RIGHT: EIcon;
        private static _BOLD;
        static BOLD: EIcon;
        private static _CHAIN;
        static CHAIN: EIcon;
        private static _CHAIN_BROKEN;
        static CHAIN_BROKEN: EIcon;
        private static _CLIPBOARD;
        static CLIPBOARD: EIcon;
        private static _COLUMNS;
        static COLUMNS: EIcon;
        private static _COPY;
        static COPY: EIcon;
        private static _CUT;
        static CUT: EIcon;
        private static _DEDENT;
        static DEDENT: EIcon;
        private static _FILES_O;
        static FILES_O: EIcon;
        private static _FLOPPY_O;
        static FLOPPY_O: EIcon;
        private static _FONT;
        static FONT: EIcon;
        private static _HEADER;
        static HEADER: EIcon;
        private static _INDENT;
        static INDENT: EIcon;
        private static _ITALIC;
        static ITALIC: EIcon;
        private static _LINK;
        static LINK: EIcon;
        private static _LIST;
        static LIST: EIcon;
        private static _LIST_ALT;
        static LIST_ALT: EIcon;
        private static _LIST_OL;
        static LIST_OL: EIcon;
        private static _LIST_UL;
        static LIST_UL: EIcon;
        private static _OUTDENT;
        static OUTDENT: EIcon;
        private static _PAPERCLIP;
        static PAPERCLIP: EIcon;
        private static _PARAGRAPH;
        static PARAGRAPH: EIcon;
        private static _PASTE;
        static PASTE: EIcon;
        private static _REPEAT;
        static REPEAT: EIcon;
        private static _ROTATE_LEFT;
        static ROTATE_LEFT: EIcon;
        private static _ROTATE_RIGHT;
        static ROTATE_RIGHT: EIcon;
        private static _SAVE;
        static SAVE: EIcon;
        private static _SCISSORS;
        static SCISSORS: EIcon;
        private static _STRIKETHROUGH;
        static STRIKETHROUGH: EIcon;
        private static _SUBSCRIPT;
        static SUBSCRIPT: EIcon;
        private static _SUPERSCRIPT;
        static SUPERSCRIPT: EIcon;
        private static _TABLE;
        static TABLE: EIcon;
        private static _TEXT_HEIGHT;
        static TEXT_HEIGHT: EIcon;
        private static _TEXT_WIDTH;
        static TEXT_WIDTH: EIcon;
        private static _TH;
        static TH: EIcon;
        private static _TH_LARGE;
        static TH_LARGE: EIcon;
        private static _TH_LIST;
        static TH_LIST: EIcon;
        private static _UNDERLINE;
        static UNDERLINE: EIcon;
        private static _UNDO;
        static UNDO: EIcon;
        private static _UNLINK;
        static UNLINK: EIcon;
        private static _ANGLE_DOUBLE_DOWN;
        static ANGLE_DOUBLE_DOWN: EIcon;
        private static _ANGLE_DOUBLE_LEFT;
        static ANGLE_DOUBLE_LEFT: EIcon;
        private static _ANGLE_DOUBLE_RIGHT;
        static ANGLE_DOUBLE_RIGHT: EIcon;
        private static _ANGLE_DOUBLE_UP;
        static ANGLE_DOUBLE_UP: EIcon;
        private static _ANGLE_DOWN;
        static ANGLE_DOWN: EIcon;
        private static _ANGLE_LEFT;
        static ANGLE_LEFT: EIcon;
        private static _ANGLE_RIGHT;
        static ANGLE_RIGHT: EIcon;
        private static _ANGLE_UP;
        static ANGLE_UP: EIcon;
        private static _ARROW_CIRCLE_DOWN;
        static ARROW_CIRCLE_DOWN: EIcon;
        private static _ARROW_CIRCLE_LEFT;
        static ARROW_CIRCLE_LEFT: EIcon;
        private static _ARROW_CIRCLE_O_DOWN;
        static ARROW_CIRCLE_O_DOWN: EIcon;
        private static _ARROW_CIRCLE_O_LEFT;
        static ARROW_CIRCLE_O_LEFT: EIcon;
        private static _ARROW_CIRCLE_O_RIGHT;
        static ARROW_CIRCLE_O_RIGHT: EIcon;
        private static _ARROW_CIRCLE_O_UP;
        static ARROW_CIRCLE_O_UP: EIcon;
        private static _ARROW_CIRCLE_RIGHT;
        static ARROW_CIRCLE_RIGHT: EIcon;
        private static _ARROW_CIRCLE_UP;
        static ARROW_CIRCLE_UP: EIcon;
        private static _ARROW_DOWN;
        static ARROW_DOWN: EIcon;
        private static _ARROW_LEFT;
        static ARROW_LEFT: EIcon;
        private static _ARROW_RIGHT;
        static ARROW_RIGHT: EIcon;
        private static _ARROW_UP;
        static ARROW_UP: EIcon;
        private static _ARROWS_ALT;
        static ARROWS_ALT: EIcon;
        private static _CARET_DOWN;
        static CARET_DOWN: EIcon;
        private static _CARET_LEFT;
        static CARET_LEFT: EIcon;
        private static _CARET_RIGHT;
        static CARET_RIGHT: EIcon;
        private static _CARET_UP;
        static CARET_UP: EIcon;
        private static _CHEVRON_CIRCLE_DOWN;
        static CHEVRON_CIRCLE_DOWN: EIcon;
        private static _CHEVRON_CIRCLE_LEFT;
        static CHEVRON_CIRCLE_LEFT: EIcon;
        private static _CHEVRON_CIRCLE_RIGHT;
        static CHEVRON_CIRCLE_RIGHT: EIcon;
        private static _CHEVRON_CIRCLE_UP;
        static CHEVRON_CIRCLE_UP: EIcon;
        private static _CHEVRON_DOWN;
        static CHEVRON_DOWN: EIcon;
        private static _CHEVRON_LEFT;
        static CHEVRON_LEFT: EIcon;
        private static _CHEVRON_RIGHT;
        static CHEVRON_RIGHT: EIcon;
        private static _CHEVRON_UP;
        static CHEVRON_UP: EIcon;
        private static _LONG_ARROW_DOWN;
        static LONG_ARROW_DOWN: EIcon;
        private static _LONG_ARROW_LEFT;
        static LONG_ARROW_LEFT: EIcon;
        private static _LONG_ARROW_RIGHT;
        static LONG_ARROW_RIGHT: EIcon;
        private static _LONG_ARROW_UP;
        static LONG_ARROW_UP: EIcon;
        private static _BACKWARD;
        static BACKWARD: EIcon;
        private static _COMPRESS;
        static COMPRESS: EIcon;
        private static _EJECT;
        static EJECT: EIcon;
        private static _EXPAND;
        static EXPAND: EIcon;
        private static _FAST_BACKWARD;
        static FAST_BACKWARD: EIcon;
        private static _FAST_FORWARD;
        static FAST_FORWARD: EIcon;
        private static _FORWARD;
        static FORWARD: EIcon;
        private static _PAUSE;
        static PAUSE: EIcon;
        private static _PLAY;
        static PLAY: EIcon;
        private static _PLAY_CIRCLE;
        static PLAY_CIRCLE: EIcon;
        private static _PLAY_CIRCLE_O;
        static PLAY_CIRCLE_O: EIcon;
        private static _STEP_BACKWARD;
        static STEP_BACKWARD: EIcon;
        private static _STEP_FORWARD;
        static STEP_FORWARD: EIcon;
        private static _STOP;
        static STOP: EIcon;
        private static _YOUTUBE_PLAY;
        static YOUTUBE_PLAY: EIcon;
        private static _ADN;
        static ADN: EIcon;
        private static _ANDROID;
        static ANDROID: EIcon;
        private static _ANGELLIST;
        static ANGELLIST: EIcon;
        private static _APPLE;
        static APPLE: EIcon;
        private static _BEHANCE;
        static BEHANCE: EIcon;
        private static _BEHANCE_SQUARE;
        static BEHANCE_SQUARE: EIcon;
        private static _BITBUCKET;
        static BITBUCKET: EIcon;
        private static _BITBUCKET_SQUARE;
        static BITBUCKET_SQUARE: EIcon;
        private static _BUYSELLADS;
        static BUYSELLADS: EIcon;
        private static _CODEPEN;
        static CODEPEN: EIcon;
        private static _CONNECTDEVELOP;
        static CONNECTDEVELOP: EIcon;
        private static _CSS3;
        static CSS3: EIcon;
        private static _DASHCUBE;
        static DASHCUBE: EIcon;
        private static _DELICIOUS;
        static DELICIOUS: EIcon;
        private static _DEVIANTART;
        static DEVIANTART: EIcon;
        private static _DIGG;
        static DIGG: EIcon;
        private static _DRIBBBLE;
        static DRIBBBLE: EIcon;
        private static _DROPBOX;
        static DROPBOX: EIcon;
        private static _DRUPAL;
        static DRUPAL: EIcon;
        private static _EMPIRE;
        static EMPIRE: EIcon;
        private static _FACEBOOK;
        static FACEBOOK: EIcon;
        private static _FACEBOOK_F;
        static FACEBOOK_F: EIcon;
        private static _FACEBOOK_OFFICIAL;
        static FACEBOOK_OFFICIAL: EIcon;
        private static _FACEBOOK_SQUARE;
        static FACEBOOK_SQUARE: EIcon;
        private static _FLICKR;
        static FLICKR: EIcon;
        private static _FORUMBEE;
        static FORUMBEE: EIcon;
        private static _FOURSQUARE;
        static FOURSQUARE: EIcon;
        private static _GE;
        static GE: EIcon;
        private static _GIT;
        static GIT: EIcon;
        private static _GIT_SQUARE;
        static GIT_SQUARE: EIcon;
        private static _GITHUB;
        static GITHUB: EIcon;
        private static _GITHUB_ALT;
        static GITHUB_ALT: EIcon;
        private static _GITHUB_SQUARE;
        static GITHUB_SQUARE: EIcon;
        private static _GITTIP;
        static GITTIP: EIcon;
        private static _GOOGLE;
        static GOOGLE: EIcon;
        private static _GOOGLE_PLUS;
        static GOOGLE_PLUS: EIcon;
        private static _GOOGLE_PLUS_SQUARE;
        static GOOGLE_PLUS_SQUARE: EIcon;
        private static _GRATIPAY;
        static GRATIPAY: EIcon;
        private static _HACKER_NEWS;
        static HACKER_NEWS: EIcon;
        private static _HTML5;
        static HTML5: EIcon;
        private static _INSTAGRAM;
        static INSTAGRAM: EIcon;
        private static _IOXHOST;
        static IOXHOST: EIcon;
        private static _JOOMLA;
        static JOOMLA: EIcon;
        private static _JSFIDDLE;
        static JSFIDDLE: EIcon;
        private static _LASTFM;
        static LASTFM: EIcon;
        private static _LASTFM_SQUARE;
        static LASTFM_SQUARE: EIcon;
        private static _LEANPUB;
        static LEANPUB: EIcon;
        private static _LINKEDIN;
        static LINKEDIN: EIcon;
        private static _LINKEDIN_SQUARE;
        static LINKEDIN_SQUARE: EIcon;
        private static _LINUX;
        static LINUX: EIcon;
        private static _MAXCDN;
        static MAXCDN: EIcon;
        private static _MEANPATH;
        static MEANPATH: EIcon;
        private static _MEDIUM;
        static MEDIUM: EIcon;
        private static _OPENID;
        static OPENID: EIcon;
        private static _PAGELINES;
        static PAGELINES: EIcon;
        private static _PIED_PIPER;
        static PIED_PIPER: EIcon;
        private static _PIED_PIPER_ALT;
        static PIED_PIPER_ALT: EIcon;
        private static _PINTEREST;
        static PINTEREST: EIcon;
        private static _PINTEREST_P;
        static PINTEREST_P: EIcon;
        private static _PINTEREST_SQUARE;
        static PINTEREST_SQUARE: EIcon;
        private static _QQ;
        static QQ: EIcon;
        private static _RA;
        static RA: EIcon;
        private static _REBEL;
        static REBEL: EIcon;
        private static _REDDIT;
        static REDDIT: EIcon;
        private static _REDDIT_SQUARE;
        static REDDIT_SQUARE: EIcon;
        private static _RENREN;
        static RENREN: EIcon;
        private static _SELLSY;
        static SELLSY: EIcon;
        private static _SHIRTSINBULK;
        static SHIRTSINBULK: EIcon;
        private static _SIMPLYBUILT;
        static SIMPLYBUILT: EIcon;
        private static _SKYATLAS;
        static SKYATLAS: EIcon;
        private static _SKYPE;
        static SKYPE: EIcon;
        private static _SLACK;
        static SLACK: EIcon;
        private static _SLIDESHARE;
        static SLIDESHARE: EIcon;
        private static _SOUNDCLOUD;
        static SOUNDCLOUD: EIcon;
        private static _SPOTIFY;
        static SPOTIFY: EIcon;
        private static _STACK_EXCHANGE;
        static STACK_EXCHANGE: EIcon;
        private static _STACK_OVERFLOW;
        static STACK_OVERFLOW: EIcon;
        private static _STEAM;
        static STEAM: EIcon;
        private static _STEAM_SQUARE;
        static STEAM_SQUARE: EIcon;
        private static _STUMBLEUPON;
        static STUMBLEUPON: EIcon;
        private static _STUMBLEUPON_CIRCLE;
        static STUMBLEUPON_CIRCLE: EIcon;
        private static _TENCENT_WEIBO;
        static TENCENT_WEIBO: EIcon;
        private static _TRELLO;
        static TRELLO: EIcon;
        private static _TUMBLR;
        static TUMBLR: EIcon;
        private static _TUMBLR_SQUARE;
        static TUMBLR_SQUARE: EIcon;
        private static _TWITCH;
        static TWITCH: EIcon;
        private static _TWITTER;
        static TWITTER: EIcon;
        private static _TWITTER_SQUARE;
        static TWITTER_SQUARE: EIcon;
        private static _VIACOIN;
        static VIACOIN: EIcon;
        private static _VIMEO_SQUARE;
        static VIMEO_SQUARE: EIcon;
        private static _VINE;
        static VINE: EIcon;
        private static _VK;
        static VK: EIcon;
        private static _WECHAT;
        static WECHAT: EIcon;
        private static _WEIBO;
        static WEIBO: EIcon;
        private static _WEIXIN;
        static WEIXIN: EIcon;
        private static _WHATSAPP;
        static WHATSAPP: EIcon;
        private static _WINDOWS;
        static WINDOWS: EIcon;
        private static _WORDPRESS;
        static WORDPRESS: EIcon;
        private static _XING;
        static XING: EIcon;
        private static _XING_SQUARE;
        static XING_SQUARE: EIcon;
        private static _Y_COMBINATOR_SQUARE;
        static Y_COMBINATOR_SQUARE: EIcon;
        private static _YAHOO;
        static YAHOO: EIcon;
        private static _YC_SQUARE;
        static YC_SQUARE: EIcon;
        private static _YELP;
        static YELP: EIcon;
        private static _YOUTUBE;
        static YOUTUBE: EIcon;
        private static _YOUTUBE_SQUARE;
        static YOUTUBE_SQUARE: EIcon;
        constructor(_value: string);
        className: string;
    }
}
declare namespace cubee {
    class FAIcon extends AUserControl {
        private static _initialized;
        private static initFA();
        private _size;
        private _color;
        private _spin;
        private _icon;
        private _iElement;
        private _changeListener;
        constructor(icon: EIcon);
        private refreshStyle();
        protected colorProperty(): ColorProperty;
        Color: ColorProperty;
        color: Color;
        protected sizeProperty(): NumberProperty;
        Size: NumberProperty;
        size: number;
        protected spinProperty(): BooleanProperty;
        Spin: BooleanProperty;
        spin: boolean;
        protected iconProperty(): Property<EIcon>;
        Icon: Property<EIcon>;
        icon: EIcon;
    }
}
